// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'counterJsonFile.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

CounterJsonFile _$CounterJsonFileFromJson(Map<String, dynamic> json) =>
    CounterJsonFile()
      ..tran = _Tran.fromJson(json['tran'] as Map<String, dynamic>);

Map<String, dynamic> _$CounterJsonFileToJson(CounterJsonFile instance) =>
    <String, dynamic>{
      'tran': instance.tran.toJson(),
    };

_Tran _$TranFromJson(Map<String, dynamic> json) => _Tran(
      rcpt_no: json['rcpt_no'] as int? ?? 1,
      print_no: json['print_no'] as int? ?? 1,
      sale_date: json['sale_date'] as String? ?? '0000-00-00',
      last_sale_date: json['last_sale_date'] as String? ?? '0000-00-00',
      receipt_no: json['receipt_no'] as int? ?? 1,
      debit_no: json['debit_no'] as int? ?? 1,
      credit_no: json['credit_no'] as int? ?? 1,
      last_ej_bkup: json['last_ej_bkup'] as String? ?? '0000-00-00',
      last_data_bkup: json['last_data_bkup'] as String? ?? '0000-00-00',
      guarantee_no: json['guarantee_no'] as int? ?? 1,
      ttllog_all_cnt: json['ttllog_all_cnt'] as int? ?? 0,
      ttllog_m_cnt: json['ttllog_m_cnt'] as int? ?? 0,
      ttllog_bs_cnt: json['ttllog_bs_cnt'] as int? ?? 0,
      pos_no: json['pos_no'] as int? ?? 1,
      onetime_no: json['onetime_no'] as int? ?? 500001,
      cardcash_no: json['cardcash_no'] as int? ?? 800001,
      nocardcash_no: json['nocardcash_no'] as int? ?? 900001,
      cardfee_no: json['cardfee_no'] as int? ?? 1,
      othcrdt_no: json['othcrdt_no'] as int? ?? 300001,
      owncrdt_no: json['owncrdt_no'] as int? ?? 1,
      crdtcan_no: json['crdtcan_no'] as int? ?? 1,
      poppy_cnt: json['poppy_cnt'] as int? ?? 0,
      nttasp_credit_no: json['nttasp_credit_no'] as int? ?? 1,
      nttasp_corr_stat: json['nttasp_corr_stat'] as int? ?? 0,
      nttasp_corr_reno: json['nttasp_corr_reno'] as int? ?? 0,
      nttasp_corr_date: json['nttasp_corr_date'] as String? ?? '00-00 00:00:00',
      eat_in_now: json['eat_in_now'] as int? ?? 1,
      tw_no: json['tw_no'] as int? ?? 0,
      edy_pos_id: json['edy_pos_id'] as int? ?? 0,
      sip_pos_ky: json['sip_pos_ky'] as int? ?? 0,
      encrypt_PidNew: json['encrypt_PidNew'] as String? ?? '00000000',
      encrypt_ErK1di: json['encrypt_ErK1di'] as String? ?? '00000000',
      encrypt_send_date: json['encrypt_send_date'] as String? ?? '0000000000',
      encrypt_credit_no: json['encrypt_credit_no'] as String? ?? '00000',
      deliv_rct_no: json['deliv_rct_no'] as int? ?? 1,
      order_no: json['order_no'] as int? ?? 1,
      slip_no: json['slip_no'] as int? ?? 1,
      com_seq_no: json['com_seq_no'] as int? ?? 2,
      qs_at_clstime: json['qs_at_clstime'] as String? ?? '',
      qs_at_waittimer: json['qs_at_waittimer'] as int? ?? 60,
      qs_at_opndatetime: json['qs_at_opndatetime'] as String? ?? '000000000000',
      fcl_dll_fix_time: json['fcl_dll_fix_time'] as String? ?? '0000000000',
      end_saletime: json['end_saletime'] as String? ?? '0000-00-00 00:00:00',
      qs_at_cls: json['qs_at_cls'] as int? ?? 0,
      mbrdsctckt_no: json['mbrdsctckt_no'] as int? ?? 1,
      ht2980_seq_no: json['ht2980_seq_no'] as int? ?? 1,
      duty_ej_count: json['duty_ej_count'] as int? ?? 0,
      last_clr_total: json['last_clr_total'] as String? ?? '0000-00-00',
      special_user_count: json['special_user_count'] as int? ?? 1,
      mbr_prize_counter: json['mbr_prize_counter'] as int? ?? 1,
      sqrc_tct_cnt: json['sqrc_tct_cnt'] as int? ?? 1,
      P11_prize_counter: json['P11_prize_counter'] as int? ?? 1,
      P7_prize_counter: json['P7_prize_counter'] as int? ?? 1,
      p11_prize_group_counter: json['p11_prize_group_counter'] as int? ?? 1,
      strcls_counter: json['strcls_counter'] as int? ?? 0,
      stropn_counter: json['stropn_counter'] as int? ?? 0,
      last_rdly_clear: json['last_rdly_clear'] as String? ?? '0000-00-00',
      cr2_chgcin_no: json['cr2_chgcin_no'] as int? ?? 1,
      cr2_chgout_no: json['cr2_chgout_no'] as int? ?? 1,
      now_open_datetime:
          json['now_open_datetime'] as String? ?? '00000000000000',
      certificate_no: json['certificate_no'] as int? ?? 1,
      cct_seq_no: json['cct_seq_no'] as int? ?? 1,
      dpoint_proc_no: json['dpoint_proc_no'] as int? ?? 1,
      fresta_slip_no: json['fresta_slip_no'] as int? ?? 1,
      credit_no_vega: json['credit_no_vega'] as int? ?? 1,
    );

Map<String, dynamic> _$TranToJson(_Tran instance) => <String, dynamic>{
      'rcpt_no': instance.rcpt_no,
      'print_no': instance.print_no,
      'sale_date': instance.sale_date,
      'last_sale_date': instance.last_sale_date,
      'receipt_no': instance.receipt_no,
      'debit_no': instance.debit_no,
      'credit_no': instance.credit_no,
      'last_ej_bkup': instance.last_ej_bkup,
      'last_data_bkup': instance.last_data_bkup,
      'guarantee_no': instance.guarantee_no,
      'ttllog_all_cnt': instance.ttllog_all_cnt,
      'ttllog_m_cnt': instance.ttllog_m_cnt,
      'ttllog_bs_cnt': instance.ttllog_bs_cnt,
      'pos_no': instance.pos_no,
      'onetime_no': instance.onetime_no,
      'cardcash_no': instance.cardcash_no,
      'nocardcash_no': instance.nocardcash_no,
      'cardfee_no': instance.cardfee_no,
      'othcrdt_no': instance.othcrdt_no,
      'owncrdt_no': instance.owncrdt_no,
      'crdtcan_no': instance.crdtcan_no,
      'poppy_cnt': instance.poppy_cnt,
      'nttasp_credit_no': instance.nttasp_credit_no,
      'nttasp_corr_stat': instance.nttasp_corr_stat,
      'nttasp_corr_reno': instance.nttasp_corr_reno,
      'nttasp_corr_date': instance.nttasp_corr_date,
      'eat_in_now': instance.eat_in_now,
      'tw_no': instance.tw_no,
      'edy_pos_id': instance.edy_pos_id,
      'sip_pos_ky': instance.sip_pos_ky,
      'encrypt_PidNew': instance.encrypt_PidNew,
      'encrypt_ErK1di': instance.encrypt_ErK1di,
      'encrypt_send_date': instance.encrypt_send_date,
      'encrypt_credit_no': instance.encrypt_credit_no,
      'deliv_rct_no': instance.deliv_rct_no,
      'order_no': instance.order_no,
      'slip_no': instance.slip_no,
      'com_seq_no': instance.com_seq_no,
      'qs_at_clstime': instance.qs_at_clstime,
      'qs_at_waittimer': instance.qs_at_waittimer,
      'qs_at_opndatetime': instance.qs_at_opndatetime,
      'fcl_dll_fix_time': instance.fcl_dll_fix_time,
      'end_saletime': instance.end_saletime,
      'qs_at_cls': instance.qs_at_cls,
      'mbrdsctckt_no': instance.mbrdsctckt_no,
      'ht2980_seq_no': instance.ht2980_seq_no,
      'duty_ej_count': instance.duty_ej_count,
      'last_clr_total': instance.last_clr_total,
      'special_user_count': instance.special_user_count,
      'mbr_prize_counter': instance.mbr_prize_counter,
      'sqrc_tct_cnt': instance.sqrc_tct_cnt,
      'P11_prize_counter': instance.P11_prize_counter,
      'P7_prize_counter': instance.P7_prize_counter,
      'p11_prize_group_counter': instance.p11_prize_group_counter,
      'strcls_counter': instance.strcls_counter,
      'stropn_counter': instance.stropn_counter,
      'last_rdly_clear': instance.last_rdly_clear,
      'cr2_chgcin_no': instance.cr2_chgcin_no,
      'cr2_chgout_no': instance.cr2_chgout_no,
      'now_open_datetime': instance.now_open_datetime,
      'certificate_no': instance.certificate_no,
      'cct_seq_no': instance.cct_seq_no,
      'dpoint_proc_no': instance.dpoint_proc_no,
      'fresta_slip_no': instance.fresta_slip_no,
      'credit_no_vega': instance.credit_no_vega,
    };
