// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'mergeJsonFile.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

MergeJsonFile _$MergeJsonFileFromJson(Map<String, dynamic> json) =>
    MergeJsonFile()
      ..merge = _Merge.fromJson(json['merge'] as Map<String, dynamic>)
      ..quick_data =
          _Quick_data.fromJson(json['quick_data'] as Map<String, dynamic>)
      ..resetup_data =
          _Resetup_data.fromJson(json['resetup_data'] as Map<String, dynamic>);

Map<String, dynamic> _$MergeJsonFileToJson(MergeJsonFile instance) =>
    <String, dynamic>{
      'merge': instance.merge.toJson(),
      'quick_data': instance.quick_data.toJson(),
      'resetup_data': instance.resetup_data.toJson(),
    };

_Merge _$MergeFromJson(Map<String, dynamic> json) => _Merge(
      file01: json['file01'] as String? ?? 'changer.json',
      file02: json['file02'] as String? ?? 'counter.json',
      file03: json['file03'] as String? ?? 'gcat.json',
      file04: json['file04'] as String? ?? 'mac_info.json',
      file05: json['file05'] as String? ?? 'pana_gcat.json',
      file06: json['file06'] as String? ?? 'sprt.json',
      file07: json['file07'] as String? ?? 'sys.json',
      file08: json['file08'] as String? ?? 'sys_param.json',
      file09: json['file09'] as String? ?? 'recogkey_data.json',
      file10: json['file10'] as String? ?? 'hqftp.json',
      file11: json['file11'] as String? ?? 'hqhist.json',
      file12: json['file12'] as String? ?? 'mupdate_counter.json',
      file13: json['file13'] as String? ?? 'update_counter.json',
      file14: json['file14'] as String? ?? 'fjss.json',
      file15: json['file15'] as String? ?? 'eat_in.json',
      file16: json['file16'] as String? ?? 'backupdata.json',
      file17: json['file17'] as String? ?? 'sound.json',
      file18: json['file18'] as String? ?? 'specificftp.json',
      file19: json['file19'] as String? ?? 'suica.json',
      file20: json['file20'] as String? ?? 'sm_scalesc_scl.json',
      file21: json['file21'] as String? ?? 'sm_scalesc_signp.json',
      file22: json['file22'] as String? ?? 'mm_abj.json',
      file23: json['file23'] as String? ?? 'scan_plus_1.json',
      file24: json['file24'] as String? ?? 'rsvsetup_SAPPORO.json',
      file25: json['file25'] as String? ?? 'movie_info.json',
      file26: json['file26'] as String? ?? 'qs_movie_start_dsp.json',
      file27: json['file27'] as String? ?? 'reserv.json',
      file28: json['file28'] as String? ?? 'pmouse_2800_1.json',
      file29: json['file29'] as String? ?? 'pmouse_2800_2.json',
      file30: json['file30'] as String? ?? 'image.json',
      file31: json['file31'] as String? ?? 'pmouse_2500_1.json',
      file32: json['file32'] as String? ?? 'pmouse_2500_2.json',
      file33: json['file33'] as String? ?? 'pbchg.json',
      file34: json['file34'] as String? ?? 'rsv_custreal.json',
      file35: json['file35'] as String? ?? 'wiz_cnct.json',
      file36: json['file36'] as String? ?? 'qcashier.json',
      file37: json['file37'] as String? ?? 'pmouse_plus2_1.json',
      file38: json['file38'] as String? ?? 'mbrreal.json',
      file39: json['file39'] as String? ?? 'chkr_save.json',
      file40: json['file40'] as String? ?? 'SystemCheck.json',
      file41: json['file41'] as String? ?? 'scan_2800ip_2.json',
      file42: json['file42'] as String? ?? 'speeza.json',
      file43: json['file43'] as String? ?? 'scan_plus_2.json',
      file44: json['file44'] as String? ?? 'masr.json',
      file45: json['file45'] as String? ?? 'qc_start_dsp.json',
      file46: json['file46'] as String? ?? 'speeza_com.json',
      file47: json['file47'] as String? ?? 'custreal_nec.json',
      file50: json['file50'] as String? ?? 'nttd_preca.json',
      file51: json['file51'] as String? ?? 'mc_param.json',
      file52: json['file52'] as String? ?? 'wol.json',
      file53: json['file53'] as String? ?? 'counter_JC_C.json',
      file54: json['file54'] as String? ?? 'mac_info_JC_C.json',
      file55: json['file55'] as String? ?? 'TccUts.json',
      file56: json['file56'] as String? ?? 'main_menu.json',
      file57: json['file57'] as String? ?? 'add_parts.json',
      file58: json['file58'] as String? ?? 'cnct_sio.json',
      file59: json['file59'] as String? ?? 'hq_set.json',
      file60: json['file60'] as String? ?? 'fal2_spec.json',
      file61: json['file61'] as String? ?? 'msr_chk.json',
      file62: json['file62'] as String? ?? 'mm_rept_taxchg.json',
      file63: json['file63'] as String? ?? 'set_option.json',
      file64: json['file64'] as String? ?? 'fal2_spec.json',
      file65: json['file65'] as String? ?? 'battery.json',
      file66: json['file66'] as String? ?? 'f_self_content.json',
      file67: json['file67'] as String? ?? 'pmouse_2800_3.json',
      file68: json['file68'] as String? ?? 'f_self_img.json',
      file69: json['file69'] as String? ?? 'trk_preca.json',
      file70: json['file70'] as String? ?? 'repica.json',
      file71: json['file71'] as String? ?? 'lottery.json',
      file72: json['file72'] as String? ?? 'cogca.json',
      file73: json['file73'] as String? ?? 'auto_update.json',
      file74: json['file74'] as String? ?? 'tprtim_counter.json',
      file75: json['file75'] as String? ?? 'devread.json',
      file76: json['file76'] as String? ?? 'ecs_spec.json',
      file77: json['file77'] as String? ?? 'recogkey_activate.json',
      file78: json['file78'] as String? ?? 'msr_int_1.json',
      file79: json['file79'] as String? ?? 'f_self_hp_img.json',
      file80: json['file80'] as String? ?? 'vacuum_date.json',
      file81: json['file81'] as String? ?? 'pmouse_2800_4.json',
      file82: json['file82'] as String? ?? 'barcode_pay.json',
      file83: json['file83'] as String? ?? 'powli.json',
      file84: json['file84'] as String? ?? 'webapi_key.json',
      file85: json['file85'] as String? ?? 'custreal_ajs.json',
      file86: json['file86'] as String? ?? 'ecs_fw.json',
      file87: json['file87'] as String? ?? 'pmouse_5900_1.json',
      file88: json['file88'] as String? ?? 'taxfree.json',
      file89: json['file89'] as String? ?? 'mail_sender.json',
      file90: json['file90'] as String? ?? 'pmouse_2800_5.json',
      file91: json['file91'] as String? ?? 'f_self_vfhd_hp_img.json',
      file92: json['file92'] as String? ?? 'valuecard.json',
      file93: json['file93'] as String? ?? 'pmouse_2800_6.json',
      file94: json['file94'] as String? ?? 'pmouse_2800_7.json',
      file95: json['file95'] as String? ?? 'rpoint.json',
      file96: json['file96'] as String? ?? 'tpoint.json',
      file97: json['file97'] as String? ?? 'net_receipt.json',
      file98: json['file98'] as String? ?? 'tomoIF.json',
      file99: json['file99'] as String? ?? 'acttrigger.json',
      file100: json['file100'] as String? ?? 'cust_fresta.json',
      file101: json['file101'] as String? ?? 'cust_istyle.json',
      file_cnt: json['file_cnt'] as int? ?? 101,
    );

Map<String, dynamic> _$MergeToJson(_Merge instance) => <String, dynamic>{
      'file01': instance.file01,
      'file02': instance.file02,
      'file03': instance.file03,
      'file04': instance.file04,
      'file05': instance.file05,
      'file06': instance.file06,
      'file07': instance.file07,
      'file08': instance.file08,
      'file09': instance.file09,
      'file10': instance.file10,
      'file11': instance.file11,
      'file12': instance.file12,
      'file13': instance.file13,
      'file14': instance.file14,
      'file15': instance.file15,
      'file16': instance.file16,
      'file17': instance.file17,
      'file18': instance.file18,
      'file19': instance.file19,
      'file20': instance.file20,
      'file21': instance.file21,
      'file22': instance.file22,
      'file23': instance.file23,
      'file24': instance.file24,
      'file25': instance.file25,
      'file26': instance.file26,
      'file27': instance.file27,
      'file28': instance.file28,
      'file29': instance.file29,
      'file30': instance.file30,
      'file31': instance.file31,
      'file32': instance.file32,
      'file33': instance.file33,
      'file34': instance.file34,
      'file35': instance.file35,
      'file36': instance.file36,
      'file37': instance.file37,
      'file38': instance.file38,
      'file39': instance.file39,
      'file40': instance.file40,
      'file41': instance.file41,
      'file42': instance.file42,
      'file43': instance.file43,
      'file44': instance.file44,
      'file45': instance.file45,
      'file46': instance.file46,
      'file47': instance.file47,
      'file50': instance.file50,
      'file51': instance.file51,
      'file52': instance.file52,
      'file53': instance.file53,
      'file54': instance.file54,
      'file55': instance.file55,
      'file56': instance.file56,
      'file57': instance.file57,
      'file58': instance.file58,
      'file59': instance.file59,
      'file60': instance.file60,
      'file61': instance.file61,
      'file62': instance.file62,
      'file63': instance.file63,
      'file64': instance.file64,
      'file65': instance.file65,
      'file66': instance.file66,
      'file67': instance.file67,
      'file68': instance.file68,
      'file69': instance.file69,
      'file70': instance.file70,
      'file71': instance.file71,
      'file72': instance.file72,
      'file73': instance.file73,
      'file74': instance.file74,
      'file75': instance.file75,
      'file76': instance.file76,
      'file77': instance.file77,
      'file78': instance.file78,
      'file79': instance.file79,
      'file80': instance.file80,
      'file81': instance.file81,
      'file82': instance.file82,
      'file83': instance.file83,
      'file84': instance.file84,
      'file85': instance.file85,
      'file86': instance.file86,
      'file87': instance.file87,
      'file88': instance.file88,
      'file89': instance.file89,
      'file90': instance.file90,
      'file91': instance.file91,
      'file92': instance.file92,
      'file93': instance.file93,
      'file94': instance.file94,
      'file95': instance.file95,
      'file96': instance.file96,
      'file97': instance.file97,
      'file98': instance.file98,
      'file99': instance.file99,
      'file100': instance.file100,
      'file101': instance.file101,
      'file_cnt': instance.file_cnt,
    };

_Quick_data _$Quick_dataFromJson(Map<String, dynamic> json) => _Quick_data(
      file_cnt: json['file_cnt'] as int? ?? 31,
      file01: json['file01'] as String? ?? 'version.json',
      file02: json['file02'] as String? ?? 'counter.json',
      file03: json['file03'] as String? ?? 'recogkey_data.json',
      file04: json['file04'] as String? ?? 'mupdate_counter.json',
      file05: json['file05'] as String? ?? 'update_counter.json',
      file06: json['file06'] as String? ?? 'eat_in.json',
      file07: json['file07'] as String? ?? 'suica.json',
      file08: json['file08'] as String? ?? 'mm_abj.json',
      file09: json['file09'] as String? ?? 'pmouse_2800_1.json',
      file10: json['file10'] as String? ?? 'pmouse_2800_2.json',
      file11: json['file11'] as String? ?? 'pmouse_2500_1.json',
      file12: json['file12'] as String? ?? 'pmouse_2500_2.json',
      file13: json['file13'] as String? ?? 'pbchg.json',
      file14: json['file14'] as String? ?? 'pmouse_plus2_1.json',
      file15: json['file15'] as String? ?? 'counter_JC_C.json',
      file16: json['file16'] as String? ?? 'battery.json',
      file17: json['file17'] as String? ?? 'pmouse_2800_3.json',
      file18: json['file18'] as String? ?? 'repica.json',
      file19: json['file19'] as String? ?? 'auto_update.json',
      file20: json['file20'] as String? ?? 'tprtim_counter.json',
      file21: json['file21'] as String? ?? 'devread.json',
      file22: json['file22'] as String? ?? 'vacuum_date.json',
      file23: json['file23'] as String? ?? 'pmouse_2800_4.json',
      file24: json['file24'] as String? ?? 'ecs_fw.json',
      file25: json['file25'] as String? ?? 'pmouse_5900_1.json',
      file26: json['file26'] as String? ?? 'pmouse_2800_5.json',
      file27: json['file27'] as String? ?? 'pmouse_2800_6.json',
      file28: json['file28'] as String? ?? 'pmouse_2800_7.json',
      file29: json['file29'] as String? ?? 'taxfree.json',
      file30: json['file30'] as String? ?? 'auto_strcls_tran.json',
      file31: json['file31'] as String? ?? 'acttrigger.json',
    );

Map<String, dynamic> _$Quick_dataToJson(_Quick_data instance) =>
    <String, dynamic>{
      'file_cnt': instance.file_cnt,
      'file01': instance.file01,
      'file02': instance.file02,
      'file03': instance.file03,
      'file04': instance.file04,
      'file05': instance.file05,
      'file06': instance.file06,
      'file07': instance.file07,
      'file08': instance.file08,
      'file09': instance.file09,
      'file10': instance.file10,
      'file11': instance.file11,
      'file12': instance.file12,
      'file13': instance.file13,
      'file14': instance.file14,
      'file15': instance.file15,
      'file16': instance.file16,
      'file17': instance.file17,
      'file18': instance.file18,
      'file19': instance.file19,
      'file20': instance.file20,
      'file21': instance.file21,
      'file22': instance.file22,
      'file23': instance.file23,
      'file24': instance.file24,
      'file25': instance.file25,
      'file26': instance.file26,
      'file27': instance.file27,
      'file28': instance.file28,
      'file29': instance.file29,
      'file30': instance.file30,
      'file31': instance.file31,
    };

_Resetup_data _$Resetup_dataFromJson(Map<String, dynamic> json) =>
    _Resetup_data(
      file_cnt: json['file_cnt'] as int? ?? 12,
      file01: json['file01'] as String? ?? 'pmouse_2800_1.json',
      file02: json['file02'] as String? ?? 'pmouse_2800_2.json',
      file03: json['file03'] as String? ?? 'pmouse_2500_1.json',
      file04: json['file04'] as String? ?? 'pmouse_2500_2.json',
      file05: json['file05'] as String? ?? 'pmouse_plus2_1.json',
      file06: json['file06'] as String? ?? 'pmouse_2800_3.json',
      file07: json['file07'] as String? ?? 'pmouse_2800_4.json',
      file08: json['file08'] as String? ?? 'pmouse_2800_5.json',
      file09: json['file09'] as String? ?? 'ecs_fw.json',
      file10: json['file10'] as String? ?? 'pmouse_5900_1.json',
      file11: json['file11'] as String? ?? 'pmouse_2800_6.json',
      file12: json['file12'] as String? ?? 'pmouse_2800_7.json',
    );

Map<String, dynamic> _$Resetup_dataToJson(_Resetup_data instance) =>
    <String, dynamic>{
      'file_cnt': instance.file_cnt,
      'file01': instance.file01,
      'file02': instance.file02,
      'file03': instance.file03,
      'file04': instance.file04,
      'file05': instance.file05,
      'file06': instance.file06,
      'file07': instance.file07,
      'file08': instance.file08,
      'file09': instance.file09,
      'file10': instance.file10,
      'file11': instance.file11,
      'file12': instance.file12,
    };
