// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'speeza_jJsonFile.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Speeza_jJsonFile _$Speeza_jJsonFileFromJson(Map<String, dynamic> json) =>
    Speeza_jJsonFile()
      ..common = _Common.fromJson(json['common'] as Map<String, dynamic>)
      ..screen0 = _Screen0.fromJson(json['screen0'] as Map<String, dynamic>)
      ..screen1 = _Screen1.fromJson(json['screen1'] as Map<String, dynamic>)
      ..screen2 = _Screen2.fromJson(json['screen2'] as Map<String, dynamic>)
      ..screen3 = _Screen3.fromJson(json['screen3'] as Map<String, dynamic>)
      ..screen4 = _Screen4.fromJson(json['screen4'] as Map<String, dynamic>)
      ..screen5 = _Screen5.fromJson(json['screen5'] as Map<String, dynamic>)
      ..screen6 = _Screen6.fromJson(json['screen6'] as Map<String, dynamic>)
      ..screen7 = _Screen7.fromJson(json['screen7'] as Map<String, dynamic>)
      ..screen8 = _Screen8.fromJson(json['screen8'] as Map<String, dynamic>)
      ..screen9 = _Screen9.fromJson(json['screen9'] as Map<String, dynamic>);

Map<String, dynamic> _$Speeza_jJsonFileToJson(Speeza_jJsonFile instance) =>
    <String, dynamic>{
      'common': instance.common.toJson(),
      'screen0': instance.screen0.toJson(),
      'screen1': instance.screen1.toJson(),
      'screen2': instance.screen2.toJson(),
      'screen3': instance.screen3.toJson(),
      'screen4': instance.screen4.toJson(),
      'screen5': instance.screen5.toJson(),
      'screen6': instance.screen6.toJson(),
      'screen7': instance.screen7.toJson(),
      'screen8': instance.screen8.toJson(),
      'screen9': instance.screen9.toJson(),
    };

_Common _$CommonFromJson(Map<String, dynamic> json) => _Common(
      page_max: json['page_max'] as int? ?? 10,
    );

Map<String, dynamic> _$CommonToJson(_Common instance) => <String, dynamic>{
      'page_max': instance.page_max,
    };

_Screen0 _$Screen0FromJson(Map<String, dynamic> json) => _Screen0(
      title: json['title'] as String? ?? 'スタート画面',
      line1: json['line1'] as String? ?? 'いらっしゃいませ',
      line2: json['line2'] as String? ?? '',
      line1_ex: json['line1_ex'] as String? ?? '',
      line2_ex: json['line2_ex'] as String? ?? '',
      line1_cn: json['line1_cn'] as String? ?? '',
      line2_cn: json['line2_cn'] as String? ?? '',
      line1_kor: json['line1_kor'] as String? ?? '',
      line2_kor: json['line2_kor'] as String? ?? '',
      msg1: json['msg1'] as String? ?? 'ボタンを選択し',
      msg2: json['msg2'] as String? ?? '登録をスタートしてください',
      msg3: json['msg3'] as String? ?? '',
      msg4: json['msg4'] as String? ?? '',
      msg1_ex: json['msg1_ex'] as String? ?? '',
      msg2_ex: json['msg2_ex'] as String? ?? '',
      msg3_ex: json['msg3_ex'] as String? ?? '',
      msg4_ex: json['msg4_ex'] as String? ?? '',
      msg1_cn: json['msg1_cn'] as String? ?? '',
      msg2_cn: json['msg2_cn'] as String? ?? '',
      msg3_cn: json['msg3_cn'] as String? ?? '',
      msg4_cn: json['msg4_cn'] as String? ?? '',
      msg1_kor: json['msg1_kor'] as String? ?? '',
      msg2_kor: json['msg2_kor'] as String? ?? '',
      msg3_kor: json['msg3_kor'] as String? ?? '',
      msg4_kor: json['msg4_kor'] as String? ?? '',
      etc1: json['etc1'] as String? ?? '',
      etc2: json['etc2'] as String? ?? '',
      etc3: json['etc3'] as String? ?? '',
      etc4: json['etc4'] as String? ?? '',
      etc5: json['etc5'] as String? ?? '',
      etc1_ex: json['etc1_ex'] as String? ?? '',
      etc2_ex: json['etc2_ex'] as String? ?? '',
      etc3_ex: json['etc3_ex'] as String? ?? '',
      etc4_ex: json['etc4_ex'] as String? ?? '',
      etc5_ex: json['etc5_ex'] as String? ?? '',
      etc1_cn: json['etc1_cn'] as String? ?? '',
      etc2_cn: json['etc2_cn'] as String? ?? '',
      etc3_cn: json['etc3_cn'] as String? ?? '',
      etc4_cn: json['etc4_cn'] as String? ?? '',
      etc5_cn: json['etc5_cn'] as String? ?? '',
      etc1_kor: json['etc1_kor'] as String? ?? '',
      etc2_kor: json['etc2_kor'] as String? ?? '',
      etc3_kor: json['etc3_kor'] as String? ?? '',
      etc4_kor: json['etc4_kor'] as String? ?? '',
      etc5_kor: json['etc5_kor'] as String? ?? '',
    );

Map<String, dynamic> _$Screen0ToJson(_Screen0 instance) => <String, dynamic>{
      'title': instance.title,
      'line1': instance.line1,
      'line2': instance.line2,
      'line1_ex': instance.line1_ex,
      'line2_ex': instance.line2_ex,
      'line1_cn': instance.line1_cn,
      'line2_cn': instance.line2_cn,
      'line1_kor': instance.line1_kor,
      'line2_kor': instance.line2_kor,
      'msg1': instance.msg1,
      'msg2': instance.msg2,
      'msg3': instance.msg3,
      'msg4': instance.msg4,
      'msg1_ex': instance.msg1_ex,
      'msg2_ex': instance.msg2_ex,
      'msg3_ex': instance.msg3_ex,
      'msg4_ex': instance.msg4_ex,
      'msg1_cn': instance.msg1_cn,
      'msg2_cn': instance.msg2_cn,
      'msg3_cn': instance.msg3_cn,
      'msg4_cn': instance.msg4_cn,
      'msg1_kor': instance.msg1_kor,
      'msg2_kor': instance.msg2_kor,
      'msg3_kor': instance.msg3_kor,
      'msg4_kor': instance.msg4_kor,
      'etc1': instance.etc1,
      'etc2': instance.etc2,
      'etc3': instance.etc3,
      'etc4': instance.etc4,
      'etc5': instance.etc5,
      'etc1_ex': instance.etc1_ex,
      'etc2_ex': instance.etc2_ex,
      'etc3_ex': instance.etc3_ex,
      'etc4_ex': instance.etc4_ex,
      'etc5_ex': instance.etc5_ex,
      'etc1_cn': instance.etc1_cn,
      'etc2_cn': instance.etc2_cn,
      'etc3_cn': instance.etc3_cn,
      'etc4_cn': instance.etc4_cn,
      'etc5_cn': instance.etc5_cn,
      'etc1_kor': instance.etc1_kor,
      'etc2_kor': instance.etc2_kor,
      'etc3_kor': instance.etc3_kor,
      'etc4_kor': instance.etc4_kor,
      'etc5_kor': instance.etc5_kor,
    };

_Screen1 _$Screen1FromJson(Map<String, dynamic> json) => _Screen1(
      title: json['title'] as String? ?? 'スタート画面',
      line1: json['line1'] as String? ?? '',
      line2: json['line2'] as String? ?? '',
      line1_ex: json['line1_ex'] as String? ?? '',
      line2_ex: json['line2_ex'] as String? ?? '',
      line1_cn: json['line1_cn'] as String? ?? '',
      line2_cn: json['line2_cn'] as String? ?? '',
      line1_kor: json['line1_kor'] as String? ?? '',
      line2_kor: json['line2_kor'] as String? ?? '',
      msg1: json['msg1'] as String? ?? '登録スタートボタンを押すか',
      msg2: json['msg2'] as String? ?? '商品をスキャンしてください。',
      msg3: json['msg3'] as String? ?? '',
      msg4: json['msg4'] as String? ?? '',
      msg1_ex: json['msg1_ex'] as String? ?? '',
      msg2_ex: json['msg2_ex'] as String? ?? '',
      msg3_ex: json['msg3_ex'] as String? ?? '',
      msg4_ex: json['msg4_ex'] as String? ?? '',
      msg1_cn: json['msg1_cn'] as String? ?? '',
      msg2_cn: json['msg2_cn'] as String? ?? '',
      msg3_cn: json['msg3_cn'] as String? ?? '',
      msg4_cn: json['msg4_cn'] as String? ?? '',
      msg1_kor: json['msg1_kor'] as String? ?? '',
      msg2_kor: json['msg2_kor'] as String? ?? '',
      msg3_kor: json['msg3_kor'] as String? ?? '',
      msg4_kor: json['msg4_kor'] as String? ?? '',
      etc1: json['etc1'] as String? ?? '',
      etc2: json['etc2'] as String? ?? '',
      etc3: json['etc3'] as String? ?? '',
      etc4: json['etc4'] as String? ?? '',
      etc5: json['etc5'] as String? ?? '',
      etc1_ex: json['etc1_ex'] as String? ?? '',
      etc2_ex: json['etc2_ex'] as String? ?? '',
      etc3_ex: json['etc3_ex'] as String? ?? '',
      etc4_ex: json['etc4_ex'] as String? ?? '',
      etc5_ex: json['etc5_ex'] as String? ?? '',
      etc1_cn: json['etc1_cn'] as String? ?? '',
      etc2_cn: json['etc2_cn'] as String? ?? '',
      etc3_cn: json['etc3_cn'] as String? ?? '',
      etc4_cn: json['etc4_cn'] as String? ?? '',
      etc5_cn: json['etc5_cn'] as String? ?? '',
      etc1_kor: json['etc1_kor'] as String? ?? '',
      etc2_kor: json['etc2_kor'] as String? ?? '',
      etc3_kor: json['etc3_kor'] as String? ?? '',
      etc4_kor: json['etc4_kor'] as String? ?? '',
      etc5_kor: json['etc5_kor'] as String? ?? '',
    );

Map<String, dynamic> _$Screen1ToJson(_Screen1 instance) => <String, dynamic>{
      'title': instance.title,
      'line1': instance.line1,
      'line2': instance.line2,
      'line1_ex': instance.line1_ex,
      'line2_ex': instance.line2_ex,
      'line1_cn': instance.line1_cn,
      'line2_cn': instance.line2_cn,
      'line1_kor': instance.line1_kor,
      'line2_kor': instance.line2_kor,
      'msg1': instance.msg1,
      'msg2': instance.msg2,
      'msg3': instance.msg3,
      'msg4': instance.msg4,
      'msg1_ex': instance.msg1_ex,
      'msg2_ex': instance.msg2_ex,
      'msg3_ex': instance.msg3_ex,
      'msg4_ex': instance.msg4_ex,
      'msg1_cn': instance.msg1_cn,
      'msg2_cn': instance.msg2_cn,
      'msg3_cn': instance.msg3_cn,
      'msg4_cn': instance.msg4_cn,
      'msg1_kor': instance.msg1_kor,
      'msg2_kor': instance.msg2_kor,
      'msg3_kor': instance.msg3_kor,
      'msg4_kor': instance.msg4_kor,
      'etc1': instance.etc1,
      'etc2': instance.etc2,
      'etc3': instance.etc3,
      'etc4': instance.etc4,
      'etc5': instance.etc5,
      'etc1_ex': instance.etc1_ex,
      'etc2_ex': instance.etc2_ex,
      'etc3_ex': instance.etc3_ex,
      'etc4_ex': instance.etc4_ex,
      'etc5_ex': instance.etc5_ex,
      'etc1_cn': instance.etc1_cn,
      'etc2_cn': instance.etc2_cn,
      'etc3_cn': instance.etc3_cn,
      'etc4_cn': instance.etc4_cn,
      'etc5_cn': instance.etc5_cn,
      'etc1_kor': instance.etc1_kor,
      'etc2_kor': instance.etc2_kor,
      'etc3_kor': instance.etc3_kor,
      'etc4_kor': instance.etc4_kor,
      'etc5_kor': instance.etc5_kor,
    };

_Screen2 _$Screen2FromJson(Map<String, dynamic> json) => _Screen2(
      title: json['title'] as String? ?? '商品登録画面',
      line1: json['line1'] as String? ?? '商品を登録してください',
      line2: json['line2'] as String? ?? '',
      line1_ex: json['line1_ex'] as String? ?? '',
      line2_ex: json['line2_ex'] as String? ?? '',
      line1_cn: json['line1_cn'] as String? ?? '',
      line2_cn: json['line2_cn'] as String? ?? '',
      line1_kor: json['line1_kor'] as String? ?? '',
      line2_kor: json['line2_kor'] as String? ?? '',
      msg1: json['msg1'] as String? ?? 'バーコードが無い商品は',
      msg2: json['msg2'] as String? ?? '下から品目をお選びください',
      msg3: json['msg3'] as String? ?? '',
      msg4: json['msg4'] as String? ?? '',
      msg1_ex: json['msg1_ex'] as String? ?? '',
      msg2_ex: json['msg2_ex'] as String? ?? '',
      msg3_ex: json['msg3_ex'] as String? ?? '',
      msg4_ex: json['msg4_ex'] as String? ?? '',
      msg1_cn: json['msg1_cn'] as String? ?? '',
      msg2_cn: json['msg2_cn'] as String? ?? '',
      msg3_cn: json['msg3_cn'] as String? ?? '',
      msg4_cn: json['msg4_cn'] as String? ?? '',
      msg1_kor: json['msg1_kor'] as String? ?? '',
      msg2_kor: json['msg2_kor'] as String? ?? '',
      msg3_kor: json['msg3_kor'] as String? ?? '',
      msg4_kor: json['msg4_kor'] as String? ?? '',
      etc1: json['etc1'] as String? ?? '買上点数',
      etc2: json['etc2'] as String? ?? '点',
      etc3: json['etc3'] as String? ?? '合計',
      etc4: json['etc4'] as String? ?? '値下合計',
      etc5: json['etc5'] as String? ?? '残額',
      etc1_ex: json['etc1_ex'] as String? ?? '',
      etc2_ex: json['etc2_ex'] as String? ?? '',
      etc3_ex: json['etc3_ex'] as String? ?? '',
      etc4_ex: json['etc4_ex'] as String? ?? '',
      etc5_ex: json['etc5_ex'] as String? ?? '',
      etc1_cn: json['etc1_cn'] as String? ?? '',
      etc2_cn: json['etc2_cn'] as String? ?? '',
      etc3_cn: json['etc3_cn'] as String? ?? '',
      etc4_cn: json['etc4_cn'] as String? ?? '',
      etc5_cn: json['etc5_cn'] as String? ?? '',
      etc1_kor: json['etc1_kor'] as String? ?? '',
      etc2_kor: json['etc2_kor'] as String? ?? '',
      etc3_kor: json['etc3_kor'] as String? ?? '',
      etc4_kor: json['etc4_kor'] as String? ?? '',
      etc5_kor: json['etc5_kor'] as String? ?? '',
    );

Map<String, dynamic> _$Screen2ToJson(_Screen2 instance) => <String, dynamic>{
      'title': instance.title,
      'line1': instance.line1,
      'line2': instance.line2,
      'line1_ex': instance.line1_ex,
      'line2_ex': instance.line2_ex,
      'line1_cn': instance.line1_cn,
      'line2_cn': instance.line2_cn,
      'line1_kor': instance.line1_kor,
      'line2_kor': instance.line2_kor,
      'msg1': instance.msg1,
      'msg2': instance.msg2,
      'msg3': instance.msg3,
      'msg4': instance.msg4,
      'msg1_ex': instance.msg1_ex,
      'msg2_ex': instance.msg2_ex,
      'msg3_ex': instance.msg3_ex,
      'msg4_ex': instance.msg4_ex,
      'msg1_cn': instance.msg1_cn,
      'msg2_cn': instance.msg2_cn,
      'msg3_cn': instance.msg3_cn,
      'msg4_cn': instance.msg4_cn,
      'msg1_kor': instance.msg1_kor,
      'msg2_kor': instance.msg2_kor,
      'msg3_kor': instance.msg3_kor,
      'msg4_kor': instance.msg4_kor,
      'etc1': instance.etc1,
      'etc2': instance.etc2,
      'etc3': instance.etc3,
      'etc4': instance.etc4,
      'etc5': instance.etc5,
      'etc1_ex': instance.etc1_ex,
      'etc2_ex': instance.etc2_ex,
      'etc3_ex': instance.etc3_ex,
      'etc4_ex': instance.etc4_ex,
      'etc5_ex': instance.etc5_ex,
      'etc1_cn': instance.etc1_cn,
      'etc2_cn': instance.etc2_cn,
      'etc3_cn': instance.etc3_cn,
      'etc4_cn': instance.etc4_cn,
      'etc5_cn': instance.etc5_cn,
      'etc1_kor': instance.etc1_kor,
      'etc2_kor': instance.etc2_kor,
      'etc3_kor': instance.etc3_kor,
      'etc4_kor': instance.etc4_kor,
      'etc5_kor': instance.etc5_kor,
    };

_Screen3 _$Screen3FromJson(Map<String, dynamic> json) => _Screen3(
      title: json['title'] as String? ?? '商品登録画面',
      line1: json['line1'] as String? ?? '',
      line2: json['line2'] as String? ?? '',
      line1_ex: json['line1_ex'] as String? ?? '',
      line2_ex: json['line2_ex'] as String? ?? '',
      line1_cn: json['line1_cn'] as String? ?? '',
      line2_cn: json['line2_cn'] as String? ?? '',
      line1_kor: json['line1_kor'] as String? ?? '',
      line2_kor: json['line2_kor'] as String? ?? '',
      msg1: json['msg1'] as String? ?? '商品のバーコードを',
      msg2: json['msg2'] as String? ?? 'スキャナーに近づけて',
      msg3: json['msg3'] as String? ?? '登録を行ってください。',
      msg4: json['msg4'] as String? ?? '',
      msg1_ex: json['msg1_ex'] as String? ?? '',
      msg2_ex: json['msg2_ex'] as String? ?? '',
      msg3_ex: json['msg3_ex'] as String? ?? '',
      msg4_ex: json['msg4_ex'] as String? ?? '',
      msg1_cn: json['msg1_cn'] as String? ?? '',
      msg2_cn: json['msg2_cn'] as String? ?? '',
      msg3_cn: json['msg3_cn'] as String? ?? '',
      msg4_cn: json['msg4_cn'] as String? ?? '',
      msg1_kor: json['msg1_kor'] as String? ?? '',
      msg2_kor: json['msg2_kor'] as String? ?? '',
      msg3_kor: json['msg3_kor'] as String? ?? '',
      msg4_kor: json['msg4_kor'] as String? ?? '',
      etc1: json['etc1'] as String? ?? '価格',
      etc2: json['etc2'] as String? ?? '個数',
      etc3: json['etc3'] as String? ?? '値下',
      etc4: json['etc4'] as String? ?? '',
      etc5: json['etc5'] as String? ?? '',
      etc1_ex: json['etc1_ex'] as String? ?? '',
      etc2_ex: json['etc2_ex'] as String? ?? '',
      etc3_ex: json['etc3_ex'] as String? ?? '',
      etc4_ex: json['etc4_ex'] as String? ?? '',
      etc5_ex: json['etc5_ex'] as String? ?? '',
      etc1_cn: json['etc1_cn'] as String? ?? '',
      etc2_cn: json['etc2_cn'] as String? ?? '',
      etc3_cn: json['etc3_cn'] as String? ?? '',
      etc4_cn: json['etc4_cn'] as String? ?? '',
      etc5_cn: json['etc5_cn'] as String? ?? '',
      etc1_kor: json['etc1_kor'] as String? ?? '',
      etc2_kor: json['etc2_kor'] as String? ?? '',
      etc3_kor: json['etc3_kor'] as String? ?? '',
      etc4_kor: json['etc4_kor'] as String? ?? '',
      etc5_kor: json['etc5_kor'] as String? ?? '',
    );

Map<String, dynamic> _$Screen3ToJson(_Screen3 instance) => <String, dynamic>{
      'title': instance.title,
      'line1': instance.line1,
      'line2': instance.line2,
      'line1_ex': instance.line1_ex,
      'line2_ex': instance.line2_ex,
      'line1_cn': instance.line1_cn,
      'line2_cn': instance.line2_cn,
      'line1_kor': instance.line1_kor,
      'line2_kor': instance.line2_kor,
      'msg1': instance.msg1,
      'msg2': instance.msg2,
      'msg3': instance.msg3,
      'msg4': instance.msg4,
      'msg1_ex': instance.msg1_ex,
      'msg2_ex': instance.msg2_ex,
      'msg3_ex': instance.msg3_ex,
      'msg4_ex': instance.msg4_ex,
      'msg1_cn': instance.msg1_cn,
      'msg2_cn': instance.msg2_cn,
      'msg3_cn': instance.msg3_cn,
      'msg4_cn': instance.msg4_cn,
      'msg1_kor': instance.msg1_kor,
      'msg2_kor': instance.msg2_kor,
      'msg3_kor': instance.msg3_kor,
      'msg4_kor': instance.msg4_kor,
      'etc1': instance.etc1,
      'etc2': instance.etc2,
      'etc3': instance.etc3,
      'etc4': instance.etc4,
      'etc5': instance.etc5,
      'etc1_ex': instance.etc1_ex,
      'etc2_ex': instance.etc2_ex,
      'etc3_ex': instance.etc3_ex,
      'etc4_ex': instance.etc4_ex,
      'etc5_ex': instance.etc5_ex,
      'etc1_cn': instance.etc1_cn,
      'etc2_cn': instance.etc2_cn,
      'etc3_cn': instance.etc3_cn,
      'etc4_cn': instance.etc4_cn,
      'etc5_cn': instance.etc5_cn,
      'etc1_kor': instance.etc1_kor,
      'etc2_kor': instance.etc2_kor,
      'etc3_kor': instance.etc3_kor,
      'etc4_kor': instance.etc4_kor,
      'etc5_kor': instance.etc5_kor,
    };

_Screen4 _$Screen4FromJson(Map<String, dynamic> json) => _Screen4(
      title: json['title'] as String? ?? '商品登録画面',
      line1: json['line1'] as String? ?? '',
      line2: json['line2'] as String? ?? '',
      line1_ex: json['line1_ex'] as String? ?? '',
      line2_ex: json['line2_ex'] as String? ?? '',
      line1_cn: json['line1_cn'] as String? ?? '',
      line2_cn: json['line2_cn'] as String? ?? '',
      line1_kor: json['line1_kor'] as String? ?? '',
      line2_kor: json['line2_kor'] as String? ?? '',
      msg1: json['msg1'] as String? ?? 'バーコードが無い商品は',
      msg2: json['msg2'] as String? ?? '下のボタン↓を押してください',
      msg3: json['msg3'] as String? ?? '',
      msg4: json['msg4'] as String? ?? '',
      msg1_ex: json['msg1_ex'] as String? ?? '',
      msg2_ex: json['msg2_ex'] as String? ?? '',
      msg3_ex: json['msg3_ex'] as String? ?? '',
      msg4_ex: json['msg4_ex'] as String? ?? '',
      msg1_cn: json['msg1_cn'] as String? ?? '',
      msg2_cn: json['msg2_cn'] as String? ?? '',
      msg3_cn: json['msg3_cn'] as String? ?? '',
      msg4_cn: json['msg4_cn'] as String? ?? '',
      msg1_kor: json['msg1_kor'] as String? ?? '',
      msg2_kor: json['msg2_kor'] as String? ?? '',
      msg3_kor: json['msg3_kor'] as String? ?? '',
      msg4_kor: json['msg4_kor'] as String? ?? '',
      etc1: json['etc1'] as String? ?? '価格',
      etc2: json['etc2'] as String? ?? '個数',
      etc3: json['etc3'] as String? ?? '値下',
      etc4: json['etc4'] as String? ?? '',
      etc5: json['etc5'] as String? ?? '',
      etc1_ex: json['etc1_ex'] as String? ?? '',
      etc2_ex: json['etc2_ex'] as String? ?? '',
      etc3_ex: json['etc3_ex'] as String? ?? '',
      etc4_ex: json['etc4_ex'] as String? ?? '',
      etc5_ex: json['etc5_ex'] as String? ?? '',
      etc1_cn: json['etc1_cn'] as String? ?? '',
      etc2_cn: json['etc2_cn'] as String? ?? '',
      etc3_cn: json['etc3_cn'] as String? ?? '',
      etc4_cn: json['etc4_cn'] as String? ?? '',
      etc5_cn: json['etc5_cn'] as String? ?? '',
      etc1_kor: json['etc1_kor'] as String? ?? '',
      etc2_kor: json['etc2_kor'] as String? ?? '',
      etc3_kor: json['etc3_kor'] as String? ?? '',
      etc4_kor: json['etc4_kor'] as String? ?? '',
      etc5_kor: json['etc5_kor'] as String? ?? '',
    );

Map<String, dynamic> _$Screen4ToJson(_Screen4 instance) => <String, dynamic>{
      'title': instance.title,
      'line1': instance.line1,
      'line2': instance.line2,
      'line1_ex': instance.line1_ex,
      'line2_ex': instance.line2_ex,
      'line1_cn': instance.line1_cn,
      'line2_cn': instance.line2_cn,
      'line1_kor': instance.line1_kor,
      'line2_kor': instance.line2_kor,
      'msg1': instance.msg1,
      'msg2': instance.msg2,
      'msg3': instance.msg3,
      'msg4': instance.msg4,
      'msg1_ex': instance.msg1_ex,
      'msg2_ex': instance.msg2_ex,
      'msg3_ex': instance.msg3_ex,
      'msg4_ex': instance.msg4_ex,
      'msg1_cn': instance.msg1_cn,
      'msg2_cn': instance.msg2_cn,
      'msg3_cn': instance.msg3_cn,
      'msg4_cn': instance.msg4_cn,
      'msg1_kor': instance.msg1_kor,
      'msg2_kor': instance.msg2_kor,
      'msg3_kor': instance.msg3_kor,
      'msg4_kor': instance.msg4_kor,
      'etc1': instance.etc1,
      'etc2': instance.etc2,
      'etc3': instance.etc3,
      'etc4': instance.etc4,
      'etc5': instance.etc5,
      'etc1_ex': instance.etc1_ex,
      'etc2_ex': instance.etc2_ex,
      'etc3_ex': instance.etc3_ex,
      'etc4_ex': instance.etc4_ex,
      'etc5_ex': instance.etc5_ex,
      'etc1_cn': instance.etc1_cn,
      'etc2_cn': instance.etc2_cn,
      'etc3_cn': instance.etc3_cn,
      'etc4_cn': instance.etc4_cn,
      'etc5_cn': instance.etc5_cn,
      'etc1_kor': instance.etc1_kor,
      'etc2_kor': instance.etc2_kor,
      'etc3_kor': instance.etc3_kor,
      'etc4_kor': instance.etc4_kor,
      'etc5_kor': instance.etc5_kor,
    };

_Screen5 _$Screen5FromJson(Map<String, dynamic> json) => _Screen5(
      title: json['title'] as String? ?? 'プリセット画面',
      line1: json['line1'] as String? ?? '',
      line2: json['line2'] as String? ?? '商品を選択してください',
      line1_ex: json['line1_ex'] as String? ?? '',
      line2_ex: json['line2_ex'] as String? ?? '',
      line1_cn: json['line1_cn'] as String? ?? '',
      line2_cn: json['line2_cn'] as String? ?? '',
      line1_kor: json['line1_kor'] as String? ?? '',
      line2_kor: json['line2_kor'] as String? ?? '',
      msg1: json['msg1'] as String? ?? '',
      msg2: json['msg2'] as String? ?? '',
      msg3: json['msg3'] as String? ?? '',
      msg4: json['msg4'] as String? ?? '',
      msg1_ex: json['msg1_ex'] as String? ?? '',
      msg2_ex: json['msg2_ex'] as String? ?? '',
      msg3_ex: json['msg3_ex'] as String? ?? '',
      msg4_ex: json['msg4_ex'] as String? ?? '',
      msg1_cn: json['msg1_cn'] as String? ?? '',
      msg2_cn: json['msg2_cn'] as String? ?? '',
      msg3_cn: json['msg3_cn'] as String? ?? '',
      msg4_cn: json['msg4_cn'] as String? ?? '',
      msg1_kor: json['msg1_kor'] as String? ?? '',
      msg2_kor: json['msg2_kor'] as String? ?? '',
      msg3_kor: json['msg3_kor'] as String? ?? '',
      msg4_kor: json['msg4_kor'] as String? ?? '',
      etc1: json['etc1'] as String? ?? '価格',
      etc2: json['etc2'] as String? ?? '個数',
      etc3: json['etc3'] as String? ?? '値下',
      etc4: json['etc4'] as String? ?? '',
      etc5: json['etc5'] as String? ?? '',
      etc1_ex: json['etc1_ex'] as String? ?? '',
      etc2_ex: json['etc2_ex'] as String? ?? '',
      etc3_ex: json['etc3_ex'] as String? ?? '',
      etc4_ex: json['etc4_ex'] as String? ?? '',
      etc5_ex: json['etc5_ex'] as String? ?? '',
      etc1_cn: json['etc1_cn'] as String? ?? '',
      etc2_cn: json['etc2_cn'] as String? ?? '',
      etc3_cn: json['etc3_cn'] as String? ?? '',
      etc4_cn: json['etc4_cn'] as String? ?? '',
      etc5_cn: json['etc5_cn'] as String? ?? '',
      etc1_kor: json['etc1_kor'] as String? ?? '',
      etc2_kor: json['etc2_kor'] as String? ?? '',
      etc3_kor: json['etc3_kor'] as String? ?? '',
      etc4_kor: json['etc4_kor'] as String? ?? '',
      etc5_kor: json['etc5_kor'] as String? ?? '',
    );

Map<String, dynamic> _$Screen5ToJson(_Screen5 instance) => <String, dynamic>{
      'title': instance.title,
      'line1': instance.line1,
      'line2': instance.line2,
      'line1_ex': instance.line1_ex,
      'line2_ex': instance.line2_ex,
      'line1_cn': instance.line1_cn,
      'line2_cn': instance.line2_cn,
      'line1_kor': instance.line1_kor,
      'line2_kor': instance.line2_kor,
      'msg1': instance.msg1,
      'msg2': instance.msg2,
      'msg3': instance.msg3,
      'msg4': instance.msg4,
      'msg1_ex': instance.msg1_ex,
      'msg2_ex': instance.msg2_ex,
      'msg3_ex': instance.msg3_ex,
      'msg4_ex': instance.msg4_ex,
      'msg1_cn': instance.msg1_cn,
      'msg2_cn': instance.msg2_cn,
      'msg3_cn': instance.msg3_cn,
      'msg4_cn': instance.msg4_cn,
      'msg1_kor': instance.msg1_kor,
      'msg2_kor': instance.msg2_kor,
      'msg3_kor': instance.msg3_kor,
      'msg4_kor': instance.msg4_kor,
      'etc1': instance.etc1,
      'etc2': instance.etc2,
      'etc3': instance.etc3,
      'etc4': instance.etc4,
      'etc5': instance.etc5,
      'etc1_ex': instance.etc1_ex,
      'etc2_ex': instance.etc2_ex,
      'etc3_ex': instance.etc3_ex,
      'etc4_ex': instance.etc4_ex,
      'etc5_ex': instance.etc5_ex,
      'etc1_cn': instance.etc1_cn,
      'etc2_cn': instance.etc2_cn,
      'etc3_cn': instance.etc3_cn,
      'etc4_cn': instance.etc4_cn,
      'etc5_cn': instance.etc5_cn,
      'etc1_kor': instance.etc1_kor,
      'etc2_kor': instance.etc2_kor,
      'etc3_kor': instance.etc3_kor,
      'etc4_kor': instance.etc4_kor,
      'etc5_kor': instance.etc5_kor,
    };

_Screen6 _$Screen6FromJson(Map<String, dynamic> json) => _Screen6(
      title: json['title'] as String? ?? 'プリセット個数入力画面',
      line1: json['line1'] as String? ?? '個数を入力し',
      line2: json['line2'] as String? ?? '決定を押してください',
      line1_ex: json['line1_ex'] as String? ?? '',
      line2_ex: json['line2_ex'] as String? ?? '',
      line1_cn: json['line1_cn'] as String? ?? '',
      line2_cn: json['line2_cn'] as String? ?? '',
      line1_kor: json['line1_kor'] as String? ?? '',
      line2_kor: json['line2_kor'] as String? ?? '',
      msg1: json['msg1'] as String? ?? '個数を訂正する場合はクリア',
      msg2: json['msg2'] as String? ?? 'ボタンを押してください',
      msg3: json['msg3'] as String? ?? '',
      msg4: json['msg4'] as String? ?? '',
      msg1_ex: json['msg1_ex'] as String? ?? '',
      msg2_ex: json['msg2_ex'] as String? ?? '',
      msg3_ex: json['msg3_ex'] as String? ?? '',
      msg4_ex: json['msg4_ex'] as String? ?? '',
      msg1_cn: json['msg1_cn'] as String? ?? '',
      msg2_cn: json['msg2_cn'] as String? ?? '',
      msg3_cn: json['msg3_cn'] as String? ?? '',
      msg4_cn: json['msg4_cn'] as String? ?? '',
      msg1_kor: json['msg1_kor'] as String? ?? '',
      msg2_kor: json['msg2_kor'] as String? ?? '',
      msg3_kor: json['msg3_kor'] as String? ?? '',
      msg4_kor: json['msg4_kor'] as String? ?? '',
      etc1: json['etc1'] as String? ?? '価格',
      etc2: json['etc2'] as String? ?? '個数',
      etc3: json['etc3'] as String? ?? '値下',
      etc4: json['etc4'] as String? ?? '',
      etc5: json['etc5'] as String? ?? '',
      etc1_ex: json['etc1_ex'] as String? ?? '',
      etc2_ex: json['etc2_ex'] as String? ?? '',
      etc3_ex: json['etc3_ex'] as String? ?? '',
      etc4_ex: json['etc4_ex'] as String? ?? '',
      etc5_ex: json['etc5_ex'] as String? ?? '',
      etc1_cn: json['etc1_cn'] as String? ?? '',
      etc2_cn: json['etc2_cn'] as String? ?? '',
      etc3_cn: json['etc3_cn'] as String? ?? '',
      etc4_cn: json['etc4_cn'] as String? ?? '',
      etc5_cn: json['etc5_cn'] as String? ?? '',
      etc1_kor: json['etc1_kor'] as String? ?? '',
      etc2_kor: json['etc2_kor'] as String? ?? '',
      etc3_kor: json['etc3_kor'] as String? ?? '',
      etc4_kor: json['etc4_kor'] as String? ?? '',
      etc5_kor: json['etc5_kor'] as String? ?? '',
    );

Map<String, dynamic> _$Screen6ToJson(_Screen6 instance) => <String, dynamic>{
      'title': instance.title,
      'line1': instance.line1,
      'line2': instance.line2,
      'line1_ex': instance.line1_ex,
      'line2_ex': instance.line2_ex,
      'line1_cn': instance.line1_cn,
      'line2_cn': instance.line2_cn,
      'line1_kor': instance.line1_kor,
      'line2_kor': instance.line2_kor,
      'msg1': instance.msg1,
      'msg2': instance.msg2,
      'msg3': instance.msg3,
      'msg4': instance.msg4,
      'msg1_ex': instance.msg1_ex,
      'msg2_ex': instance.msg2_ex,
      'msg3_ex': instance.msg3_ex,
      'msg4_ex': instance.msg4_ex,
      'msg1_cn': instance.msg1_cn,
      'msg2_cn': instance.msg2_cn,
      'msg3_cn': instance.msg3_cn,
      'msg4_cn': instance.msg4_cn,
      'msg1_kor': instance.msg1_kor,
      'msg2_kor': instance.msg2_kor,
      'msg3_kor': instance.msg3_kor,
      'msg4_kor': instance.msg4_kor,
      'etc1': instance.etc1,
      'etc2': instance.etc2,
      'etc3': instance.etc3,
      'etc4': instance.etc4,
      'etc5': instance.etc5,
      'etc1_ex': instance.etc1_ex,
      'etc2_ex': instance.etc2_ex,
      'etc3_ex': instance.etc3_ex,
      'etc4_ex': instance.etc4_ex,
      'etc5_ex': instance.etc5_ex,
      'etc1_cn': instance.etc1_cn,
      'etc2_cn': instance.etc2_cn,
      'etc3_cn': instance.etc3_cn,
      'etc4_cn': instance.etc4_cn,
      'etc5_cn': instance.etc5_cn,
      'etc1_kor': instance.etc1_kor,
      'etc2_kor': instance.etc2_kor,
      'etc3_kor': instance.etc3_kor,
      'etc4_kor': instance.etc4_kor,
      'etc5_kor': instance.etc5_kor,
    };

_Screen7 _$Screen7FromJson(Map<String, dynamic> json) => _Screen7(
      title: json['title'] as String? ?? '商品登録中画面',
      line1: json['line1'] as String? ?? '商品は',
      line2: json['line2'] as String? ?? '買い物袋に入れてください',
      line1_ex: json['line1_ex'] as String? ?? '',
      line2_ex: json['line2_ex'] as String? ?? '',
      line1_cn: json['line1_cn'] as String? ?? '',
      line2_cn: json['line2_cn'] as String? ?? '',
      line1_kor: json['line1_kor'] as String? ?? '',
      line2_kor: json['line2_kor'] as String? ?? '',
      msg1: json['msg1'] as String? ?? '登録した商品は',
      msg2: json['msg2'] as String? ?? '買い物袋に入れてください',
      msg3: json['msg3'] as String? ?? '次の商品登録はこの画面が',
      msg4: json['msg4'] as String? ?? '消えてから行ってください',
      msg1_ex: json['msg1_ex'] as String? ?? '',
      msg2_ex: json['msg2_ex'] as String? ?? '',
      msg3_ex: json['msg3_ex'] as String? ?? '',
      msg4_ex: json['msg4_ex'] as String? ?? '',
      msg1_cn: json['msg1_cn'] as String? ?? '',
      msg2_cn: json['msg2_cn'] as String? ?? '',
      msg3_cn: json['msg3_cn'] as String? ?? '',
      msg4_cn: json['msg4_cn'] as String? ?? '',
      msg1_kor: json['msg1_kor'] as String? ?? '',
      msg2_kor: json['msg2_kor'] as String? ?? '',
      msg3_kor: json['msg3_kor'] as String? ?? '',
      msg4_kor: json['msg4_kor'] as String? ?? '',
      etc1: json['etc1'] as String? ?? '登録中',
      etc2: json['etc2'] as String? ?? '価格',
      etc3: json['etc3'] as String? ?? '',
      etc4: json['etc4'] as String? ?? '',
      etc5: json['etc5'] as String? ?? '',
      etc1_ex: json['etc1_ex'] as String? ?? '',
      etc2_ex: json['etc2_ex'] as String? ?? '',
      etc3_ex: json['etc3_ex'] as String? ?? '',
      etc4_ex: json['etc4_ex'] as String? ?? '',
      etc5_ex: json['etc5_ex'] as String? ?? '',
      etc1_cn: json['etc1_cn'] as String? ?? '',
      etc2_cn: json['etc2_cn'] as String? ?? '',
      etc3_cn: json['etc3_cn'] as String? ?? '',
      etc4_cn: json['etc4_cn'] as String? ?? '',
      etc5_cn: json['etc5_cn'] as String? ?? '',
      etc1_kor: json['etc1_kor'] as String? ?? '',
      etc2_kor: json['etc2_kor'] as String? ?? '',
      etc3_kor: json['etc3_kor'] as String? ?? '',
      etc4_kor: json['etc4_kor'] as String? ?? '',
      etc5_kor: json['etc5_kor'] as String? ?? '',
    );

Map<String, dynamic> _$Screen7ToJson(_Screen7 instance) => <String, dynamic>{
      'title': instance.title,
      'line1': instance.line1,
      'line2': instance.line2,
      'line1_ex': instance.line1_ex,
      'line2_ex': instance.line2_ex,
      'line1_cn': instance.line1_cn,
      'line2_cn': instance.line2_cn,
      'line1_kor': instance.line1_kor,
      'line2_kor': instance.line2_kor,
      'msg1': instance.msg1,
      'msg2': instance.msg2,
      'msg3': instance.msg3,
      'msg4': instance.msg4,
      'msg1_ex': instance.msg1_ex,
      'msg2_ex': instance.msg2_ex,
      'msg3_ex': instance.msg3_ex,
      'msg4_ex': instance.msg4_ex,
      'msg1_cn': instance.msg1_cn,
      'msg2_cn': instance.msg2_cn,
      'msg3_cn': instance.msg3_cn,
      'msg4_cn': instance.msg4_cn,
      'msg1_kor': instance.msg1_kor,
      'msg2_kor': instance.msg2_kor,
      'msg3_kor': instance.msg3_kor,
      'msg4_kor': instance.msg4_kor,
      'etc1': instance.etc1,
      'etc2': instance.etc2,
      'etc3': instance.etc3,
      'etc4': instance.etc4,
      'etc5': instance.etc5,
      'etc1_ex': instance.etc1_ex,
      'etc2_ex': instance.etc2_ex,
      'etc3_ex': instance.etc3_ex,
      'etc4_ex': instance.etc4_ex,
      'etc5_ex': instance.etc5_ex,
      'etc1_cn': instance.etc1_cn,
      'etc2_cn': instance.etc2_cn,
      'etc3_cn': instance.etc3_cn,
      'etc4_cn': instance.etc4_cn,
      'etc5_cn': instance.etc5_cn,
      'etc1_kor': instance.etc1_kor,
      'etc2_kor': instance.etc2_kor,
      'etc3_kor': instance.etc3_kor,
      'etc4_kor': instance.etc4_kor,
      'etc5_kor': instance.etc5_kor,
    };

_Screen8 _$Screen8FromJson(Map<String, dynamic> json) => _Screen8(
      title: json['title'] as String? ?? 'クリニックモード読込画面',
      line1: json['line1'] as String? ?? 'バーコードをスキャンしてください',
      line2: json['line2'] as String? ?? '',
      line1_ex: json['line1_ex'] as String? ?? '',
      line2_ex: json['line2_ex'] as String? ?? '',
      line1_cn: json['line1_cn'] as String? ?? '',
      line2_cn: json['line2_cn'] as String? ?? '',
      line1_kor: json['line1_kor'] as String? ?? '',
      line2_kor: json['line2_kor'] as String? ?? '',
      msg1: json['msg1'] as String? ?? 'バーコードを',
      msg2: json['msg2'] as String? ?? 'スキャナーに近づけて',
      msg3: json['msg3'] as String? ?? '精算を行ってください。',
      msg4: json['msg4'] as String? ?? '',
      msg1_ex: json['msg1_ex'] as String? ?? '',
      msg2_ex: json['msg2_ex'] as String? ?? '',
      msg3_ex: json['msg3_ex'] as String? ?? '',
      msg4_ex: json['msg4_ex'] as String? ?? '',
      msg1_cn: json['msg1_cn'] as String? ?? '',
      msg2_cn: json['msg2_cn'] as String? ?? '',
      msg3_cn: json['msg3_cn'] as String? ?? '',
      msg4_cn: json['msg4_cn'] as String? ?? '',
      msg1_kor: json['msg1_kor'] as String? ?? '',
      msg2_kor: json['msg2_kor'] as String? ?? '',
      msg3_kor: json['msg3_kor'] as String? ?? '',
      msg4_kor: json['msg4_kor'] as String? ?? '',
      etc1: json['etc1'] as String? ?? '点数',
      etc2: json['etc2'] as String? ?? '',
      etc3: json['etc3'] as String? ?? '',
      etc4: json['etc4'] as String? ?? '',
      etc5: json['etc5'] as String? ?? '',
      etc1_ex: json['etc1_ex'] as String? ?? '',
      etc2_ex: json['etc2_ex'] as String? ?? '',
      etc3_ex: json['etc3_ex'] as String? ?? '',
      etc4_ex: json['etc4_ex'] as String? ?? '',
      etc5_ex: json['etc5_ex'] as String? ?? '',
      etc1_cn: json['etc1_cn'] as String? ?? '',
      etc2_cn: json['etc2_cn'] as String? ?? '',
      etc3_cn: json['etc3_cn'] as String? ?? '',
      etc4_cn: json['etc4_cn'] as String? ?? '',
      etc5_cn: json['etc5_cn'] as String? ?? '',
      etc1_kor: json['etc1_kor'] as String? ?? '',
      etc2_kor: json['etc2_kor'] as String? ?? '',
      etc3_kor: json['etc3_kor'] as String? ?? '',
      etc4_kor: json['etc4_kor'] as String? ?? '',
      etc5_kor: json['etc5_kor'] as String? ?? '',
    );

Map<String, dynamic> _$Screen8ToJson(_Screen8 instance) => <String, dynamic>{
      'title': instance.title,
      'line1': instance.line1,
      'line2': instance.line2,
      'line1_ex': instance.line1_ex,
      'line2_ex': instance.line2_ex,
      'line1_cn': instance.line1_cn,
      'line2_cn': instance.line2_cn,
      'line1_kor': instance.line1_kor,
      'line2_kor': instance.line2_kor,
      'msg1': instance.msg1,
      'msg2': instance.msg2,
      'msg3': instance.msg3,
      'msg4': instance.msg4,
      'msg1_ex': instance.msg1_ex,
      'msg2_ex': instance.msg2_ex,
      'msg3_ex': instance.msg3_ex,
      'msg4_ex': instance.msg4_ex,
      'msg1_cn': instance.msg1_cn,
      'msg2_cn': instance.msg2_cn,
      'msg3_cn': instance.msg3_cn,
      'msg4_cn': instance.msg4_cn,
      'msg1_kor': instance.msg1_kor,
      'msg2_kor': instance.msg2_kor,
      'msg3_kor': instance.msg3_kor,
      'msg4_kor': instance.msg4_kor,
      'etc1': instance.etc1,
      'etc2': instance.etc2,
      'etc3': instance.etc3,
      'etc4': instance.etc4,
      'etc5': instance.etc5,
      'etc1_ex': instance.etc1_ex,
      'etc2_ex': instance.etc2_ex,
      'etc3_ex': instance.etc3_ex,
      'etc4_ex': instance.etc4_ex,
      'etc5_ex': instance.etc5_ex,
      'etc1_cn': instance.etc1_cn,
      'etc2_cn': instance.etc2_cn,
      'etc3_cn': instance.etc3_cn,
      'etc4_cn': instance.etc4_cn,
      'etc5_cn': instance.etc5_cn,
      'etc1_kor': instance.etc1_kor,
      'etc2_kor': instance.etc2_kor,
      'etc3_kor': instance.etc3_kor,
      'etc4_kor': instance.etc4_kor,
      'etc5_kor': instance.etc5_kor,
    };

_Screen9 _$Screen9FromJson(Map<String, dynamic> json) => _Screen9(
      title: json['title'] as String? ?? 'クリニックモード読込中画面',
      line1: json['line1'] as String? ?? '読み込んでいます',
      line2: json['line2'] as String? ?? '',
      line1_ex: json['line1_ex'] as String? ?? '',
      line2_ex: json['line2_ex'] as String? ?? '',
      line1_cn: json['line1_cn'] as String? ?? '',
      line2_cn: json['line2_cn'] as String? ?? '',
      line1_kor: json['line1_kor'] as String? ?? '',
      line2_kor: json['line2_kor'] as String? ?? '',
      msg1: json['msg1'] as String? ?? '次のバーコードをスキャンする',
      msg2: json['msg2'] as String? ?? '場合はこの画面が消えてから',
      msg3: json['msg3'] as String? ?? '行ってください',
      msg4: json['msg4'] as String? ?? '',
      msg1_ex: json['msg1_ex'] as String? ?? '',
      msg2_ex: json['msg2_ex'] as String? ?? '',
      msg3_ex: json['msg3_ex'] as String? ?? '',
      msg4_ex: json['msg4_ex'] as String? ?? '',
      msg1_cn: json['msg1_cn'] as String? ?? '',
      msg2_cn: json['msg2_cn'] as String? ?? '',
      msg3_cn: json['msg3_cn'] as String? ?? '',
      msg4_cn: json['msg4_cn'] as String? ?? '',
      msg1_kor: json['msg1_kor'] as String? ?? '',
      msg2_kor: json['msg2_kor'] as String? ?? '',
      msg3_kor: json['msg3_kor'] as String? ?? '',
      msg4_kor: json['msg4_kor'] as String? ?? '',
      etc1: json['etc1'] as String? ?? '読込中',
      etc2: json['etc2'] as String? ?? '価格',
      etc3: json['etc3'] as String? ?? '',
      etc4: json['etc4'] as String? ?? '',
      etc5: json['etc5'] as String? ?? '',
      etc1_ex: json['etc1_ex'] as String? ?? '',
      etc2_ex: json['etc2_ex'] as String? ?? '',
      etc3_ex: json['etc3_ex'] as String? ?? '',
      etc4_ex: json['etc4_ex'] as String? ?? '',
      etc5_ex: json['etc5_ex'] as String? ?? '',
      etc1_cn: json['etc1_cn'] as String? ?? '',
      etc2_cn: json['etc2_cn'] as String? ?? '',
      etc3_cn: json['etc3_cn'] as String? ?? '',
      etc4_cn: json['etc4_cn'] as String? ?? '',
      etc5_cn: json['etc5_cn'] as String? ?? '',
      etc1_kor: json['etc1_kor'] as String? ?? '',
      etc2_kor: json['etc2_kor'] as String? ?? '',
      etc3_kor: json['etc3_kor'] as String? ?? '',
      etc4_kor: json['etc4_kor'] as String? ?? '',
      etc5_kor: json['etc5_kor'] as String? ?? '',
    );

Map<String, dynamic> _$Screen9ToJson(_Screen9 instance) => <String, dynamic>{
      'title': instance.title,
      'line1': instance.line1,
      'line2': instance.line2,
      'line1_ex': instance.line1_ex,
      'line2_ex': instance.line2_ex,
      'line1_cn': instance.line1_cn,
      'line2_cn': instance.line2_cn,
      'line1_kor': instance.line1_kor,
      'line2_kor': instance.line2_kor,
      'msg1': instance.msg1,
      'msg2': instance.msg2,
      'msg3': instance.msg3,
      'msg4': instance.msg4,
      'msg1_ex': instance.msg1_ex,
      'msg2_ex': instance.msg2_ex,
      'msg3_ex': instance.msg3_ex,
      'msg4_ex': instance.msg4_ex,
      'msg1_cn': instance.msg1_cn,
      'msg2_cn': instance.msg2_cn,
      'msg3_cn': instance.msg3_cn,
      'msg4_cn': instance.msg4_cn,
      'msg1_kor': instance.msg1_kor,
      'msg2_kor': instance.msg2_kor,
      'msg3_kor': instance.msg3_kor,
      'msg4_kor': instance.msg4_kor,
      'etc1': instance.etc1,
      'etc2': instance.etc2,
      'etc3': instance.etc3,
      'etc4': instance.etc4,
      'etc5': instance.etc5,
      'etc1_ex': instance.etc1_ex,
      'etc2_ex': instance.etc2_ex,
      'etc3_ex': instance.etc3_ex,
      'etc4_ex': instance.etc4_ex,
      'etc5_ex': instance.etc5_ex,
      'etc1_cn': instance.etc1_cn,
      'etc2_cn': instance.etc2_cn,
      'etc3_cn': instance.etc3_cn,
      'etc4_cn': instance.etc4_cn,
      'etc5_cn': instance.etc5_cn,
      'etc1_kor': instance.etc1_kor,
      'etc2_kor': instance.etc2_kor,
      'etc3_kor': instance.etc3_kor,
      'etc4_kor': instance.etc4_kor,
      'etc5_kor': instance.etc5_kor,
    };
