static int DrvScanPortCheck(unsigned long fds);
static int DrvScanSerialWrite(unsigned long fds, char *sendData, unsigned long sendDataSize);
int ScanPortInit(unsigned long fds, unsigned long baudrate, unsigned long databit, unsigned long stopbit, char *parity);
int ScanPortOpen(const char *pathName, unsigned long *fds);
int ScanPortClose(unsigned long fds);
//int ScanPortInit(unsigned long fds, unsigned long baudrate, unsigned long databit, unsigned long stopbit, char *parity);
int ScanPortInit(unsigned long fds, unsigned long baudrate, unsigned long databit, unsigned long stopbit);
int ScanQCashierNormalCmd(unsigned long fds);
int ScanEnablePass(unsigned long fds);
int ScanEnable(unsigned long fds);
int ScanDisable(unsigned long fds);
int ScanHwEnableCmd(unsigned long fds);
int ScanHwDisableCmd(unsigned long fds);
int ScanPassEnableCmd(unsigned long fds);
int ScanPassDisableCmd(unsigned long fds);
int ScanPscEnableCmd(unsigned long fds);
int ScanPscDisableCmd(unsigned long fds);
int ScanDC2Cmd(unsigned long fds);
int ScanCharacterRequestCmd();
int ScanPscCmd();
int ScanDataRcv(long *fds, const char *pathName);
