#ifndef	__tprdid_h
#define	__tprdid_h

/*
 * byte or bit meanings
  +---------------+
  |a|b|c|d|e|f|g|h|
  +---------------+
   | | | | | | | +--- not use.
   | | | | | | +----- apl number or SCPU number
   | | | | | +------- systask number
   | | | | +--------- systask number
   | | | +----------- driver number
   | | +------------- driver number
   | +--------------- SCPU number
   +----------------- not use.
   see. tprdef.h
 */

#define	TPRTIDSCPU	0x0000F000	/* sub cpu */
#define	TPRTIDMECKEY	0x00000100	/* mechanical key */
#define	TPRTIDTOUKEY	0x00000200	/* touch key */
	/* reserved 	0x00000300	*/
#define	TPRTIDSPEAKER	0x00000400	/* speaker */
#define	TPRTIDFIP	0x00000500	/* FIP */
#define	TPRTIDLCDDSP	0x00000600	/* LCD */
#define	TPRTIDSCANNER	0x00000700	/* scanner */
#define	TPRTIDWDSCAN	0x00000800	/* wand scanner */
#define	TPRTIDCHANGER	0x00000900	/* changer */
#define	TPRTIDCOMUSB	0x00000A00	/* usb com convert */
#define	TPRTIDRECEIPT	0x00000B00	/* Receipt prt+Drawe */
#define	TPRTIDTOKYURW	0x00000C00	/* TOKYU Rewite card */
#define	TPRTIDDEBIT	0x00000D00	/* debit card */
#define	TPRTIDGLORYCARD	0x00000E00	/* Glory point card */
#define	TPRTIDVISMAC	0x00000F00	/* VIMAC card */
#define	TPRTIDPRSP	0x00001000	/* sp printer */
#define	TPRTIDMGC1JIS	0x00001100	/* magnetic card jis1 */
#define	TPRTIDMGC2JIS	0x00001200	/* magnetic card jis2 */
#define	TPRTIDGCAT	0x00001300	/* G-CAT */
#define	TPRTIDPRT	0x00001400	/* Print */
#define	TPRTIDLCDBRT	0x00001500	/* LCD bright */
#define	TPRTIDPMOUSE	0x00001600	/* pseudo mouse */
#define	TPRTIDSCALE	0x00001700	/* scale */
#define	TPRTIDORC	0x00001800	/* OKI rewrite card */
#define	TPRTIDSGSCALE	0x00001900	/* self-gate scale */
#define	TPRTIDSEGDISP	0x00001A00	/* Segment Display */
#define	TPRTIDCALLSW	0x00001B00	/* Clerk Call Switch */
#define	TPRTIDDETECT	0x00001C00	/* Detect Sencer */
#define TPRTIDSIGNP     0x00001D00      /* Signp Pole */
#define TPRTIDEDY       0x00001E00      /* Edy rewrite card */
#define TPRTIDCRWP      0x00001F00      /* Glory Card Read/Write Printer */
#define TPRTIDSTPR      0x00002000      /* Station Printer */
#define TPRTIDPANA      0x00002100      /* Pana Code */
#define TPRTIDGP        0x00002200      /* GP */
#define TPRTIDS2PR      0x00002000      /* S2tation Printer */
#define TPRTIDPWRCTRL   0x00002300      /* Power Control */
#define TPRTIDPW        0x00002400      /* PW410 */

#define TPRTIDCCR       0x00002500      /* CCR <2004.07.09> mn */
#define TPRTID57VFD     0x00002600      /* 5x7VFD */
#define TPRTIDDISH      0x00002700      /* dish */
#define TPRTIDAIV       0x00002800      /* HD AIVoice */
#define TPRTIDYOMOCA    0x00002900      /* Yomoca */
#define TPRTIDSMTPLUS   0x00002A00      /* Smartplus */
#define	TPRTIDSUICA	0x00002B00	/* SUICA */
#define	TPRTIDRFID	0x00002C00	/* RFID Tag Reader/Writer */
#define TPRTIDDISHT     0x00002D00      /* dish(TAKAYA) */
#define TPRTIDARSTTS    0x00002E00      /* AR-STTS-01 */
#define TPRTIDMCP    	0x00002F00	/* MCP200 */
#define TPRTIDFCL       0x00003000      /* FCL */
#define TPRTIDDRW	0x00003100	/* Drawer */
#define TPRTIDABSV31	0x00003200	/* ABS-V31 */
#define TPRTIDYAMATO    0x00003300      /* Yamato e-money */
#define TPRTIDUSBCAM	0x00003400	/* USB Camera */ 
#define TPRTIDCCT       0x00003500      /* CCT Credit */
#define TPRTIDMASR      0x00003600      /* Magnetic Auto Slide Reader */
#define TPRTIDJMUPS     0x00003700      /* J-Mups Credit */
#define TPRTIDSQRC      0x00003800      /* SQRC Ticket */

#define TPRTIDICCARD    0x00003900      /* IC CARD Reader */	/* 2015/02/02 */
#define TPRTIDMST       0x00003A00      /* MST */	/* 2015/07/14 */
#define TPRTIDPOWLI     0x00003B00      /* POWLI */
#define TPRTIDSCALERM	0x00003C00      /* RM-5900 */

#define TPRTIDPSENSOR   0x00004100      /* Proximity Sensor */
#define TPRTIDAPBF      0x00004200      /* Auto Plastic Bag Feeder */
#define TPRTIDEXC	0x00004400	/* EXC-2500 IC CARD Reader */
#define TPRTIDAMI       0x00004500      /* AMI2000 IC CARD Reader */
#define TPRTIDHITOUCH	0x00004600      /* Hitouch */
#define TPRTIDSCALE_SKS	0x00004700	/* Scale sks*/

/* input or output */
#define	TPRDEVIN		1	/* device input */
#define	TPRDEVOUT		2	/* device output */

/* result */
#define	TPRDEVRESULTOK		0	/* OK */
#define	TPRDEVRESULTTIMEOUT	1	/* Timeout */
#define	TPRDEVRESULTWERR	2	/* write err */
#define	TPRDEVRESULTEERR	3	/* Exclusive err */
#define	TPRDEVRESULTRERR	4	/* read err */
#define	TPRDEVRESULTOFFLINE	5	/* OFF line */
#define	TPRDEVRESULTPWOFF	6	/* power off */
#define	TPRDEVRESULTGIVEUP	7	/* give up... */
#define	TPRDEVRESULTTIMNOTSRT	8	/* timer not start */
#define TPRDEVRESULTCRCERR	9	/* crc check error */
#define TPRDEVRESULTRETRYOVER	10	/* retry over */

/* device id */
#define	TPRDIDSCPU1		(TPRTIDSCPU     |TPRSCPU1)
#define	TPRDIDSCPU2		(TPRTIDSCPU     |TPRSCPU2)
#define	TPRDIDSCPU3		(TPRTIDSCPU     |TPRSCPU3)
#define	TPRDIDSCPU4		(TPRTIDSCPU     |TPRSCPU4)
#define	TPRDIDSCPU5		(TPRTIDSCPU     |TPRSCPU5)
#define	TPRDIDSCPU6		(TPRTIDSCPU     |TPRSCPU6)

#define	TPRDIDMECKEY1		(TPRTIDMECKEY   |TPRSCPU1)
#define	TPRDIDMECKEY2		(TPRTIDMECKEY   |TPRSCPU2)
#define	TPRDIDMECKEY3		(TPRTIDMECKEY   |TPRSCPU3)
#define	TPRDIDMECKEY4		(TPRTIDMECKEY   |TPRSCPU4)
#define	TPRDIDMECKEY5		(TPRTIDMECKEY   |TPRSCPU5)
#define	TPRDIDMECKEY6		(TPRTIDMECKEY   |TPRSCPU6)

#define	TPRDIDTOUKEY1		(TPRTIDTOUKEY   |TPRSCPU1)
#define	TPRDIDTOUKEY2		(TPRTIDTOUKEY   |TPRSCPU2)
#define	TPRDIDTOUKEY3		(TPRTIDTOUKEY   |TPRSCPU3)
#define	TPRDIDTOUKEY4		(TPRTIDTOUKEY   |TPRSCPU4)
#define	TPRDIDTOUKEY5		(TPRTIDTOUKEY   |TPRSCPU5)
#define	TPRDIDTOUKEY6		(TPRTIDTOUKEY   |TPRSCPU6)

#define	TPRDIDSPEAKER1		(TPRTIDSPEAKER  |TPRSCPU1)
#define	TPRDIDSPEAKER2		(TPRTIDSPEAKER  |TPRSCPU2)
#define	TPRDIDSPEAKER3		(TPRTIDSPEAKER  |TPRSCPU3)
#define	TPRDIDSPEAKER4		(TPRTIDSPEAKER  |TPRSCPU4)
#define	TPRDIDSPEAKER5		(TPRTIDSPEAKER  |TPRSCPU5)
#define	TPRDIDSPEAKER6		(TPRTIDSPEAKER  |TPRSCPU6)

#define	TPRDIDFIP1		(TPRTIDFIP      |TPRSCPU1)
#define	TPRDIDFIP2		(TPRTIDFIP      |TPRSCPU2)
#define	TPRDIDFIP3		(TPRTIDFIP      |TPRSCPU3)
#define	TPRDIDFIP4		(TPRTIDFIP      |TPRSCPU4)
#define	TPRDIDFIP5		(TPRTIDFIP      |TPRSCPU5)
#define	TPRDIDFIP6		(TPRTIDFIP      |TPRSCPU6)

#define	TPRDIDLCDDSP1		(TPRTIDLCDDSP   |TPRSCPU1)
#define	TPRDIDLCDDSP2		(TPRTIDLCDDSP   |TPRSCPU2)
#define	TPRDIDLCDDSP3		(TPRTIDLCDDSP   |TPRSCPU3)
#define	TPRDIDLCDDSP4		(TPRTIDLCDDSP   |TPRSCPU4)
#define	TPRDIDLCDDSP5		(TPRTIDLCDDSP   |TPRSCPU5)
#define	TPRDIDLCDDSP6		(TPRTIDLCDDSP   |TPRSCPU6)

#define	TPRDIDSCANNER1		(TPRTIDSCANNER  |TPRSCPU1)
#define	TPRDIDSCANNER2		(TPRTIDSCANNER  |TPRSCPU2)
#define	TPRDIDSCANNER3		(TPRTIDSCANNER  |TPRSCPU3)
#define	TPRDIDSCANNER4		(TPRTIDSCANNER  |TPRSCPU4)
#define	TPRDIDSCANNER5		(TPRTIDSCANNER  |TPRSCPU5)
#define	TPRDIDSCANNER6		(TPRTIDSCANNER  |TPRSCPU6)

#define	TPRDIDWDSCAN1		(TPRTIDWDSCAN   |TPRSCPU1)
#define	TPRDIDWDSCAN2		(TPRTIDWDSCAN   |TPRSCPU2)
#define	TPRDIDWDSCAN3		(TPRTIDWDSCAN   |TPRSCPU3)
#define	TPRDIDWDSCAN4		(TPRTIDWDSCAN   |TPRSCPU4)
#define	TPRDIDWDSCAN5		(TPRTIDWDSCAN   |TPRSCPU5)
#define	TPRDIDWDSCAN6		(TPRTIDWDSCAN   |TPRSCPU6)

#define	TPRDIDCHANGER1		(TPRTIDCHANGER  |TPRSCPU1)
#define	TPRDIDCHANGER2		(TPRTIDCHANGER  |TPRSCPU2)
#define	TPRDIDCHANGER3		(TPRTIDCHANGER  |TPRSCPU3)
#define	TPRDIDCHANGER4		(TPRTIDCHANGER  |TPRSCPU4)
#define	TPRDIDCHANGER5		(TPRTIDCHANGER  |TPRSCPU5)
#define	TPRDIDCHANGER6		(TPRTIDCHANGER  |TPRSCPU6)

#define	TPRDIDCOMUSB1		(TPRTIDCOMUSB   |TPRSCPU1)
#define	TPRDIDCOMUSB2		(TPRTIDCOMUSB   |TPRSCPU2)
#define	TPRDIDCOMUSB3		(TPRTIDCOMUSB   |TPRSCPU3)
#define	TPRDIDCOMUSB4		(TPRTIDCOMUSB   |TPRSCPU4)
#define	TPRDIDCOMUSB5		(TPRTIDCOMUSB   |TPRSCPU5)
#define	TPRDIDCOMUSB6		(TPRTIDCOMUSB   |TPRSCPU6)

#define	TPRDIDRECEIPT1		(TPRTIDRECEIPT  |TPRSCPU1)
#define	TPRDIDRECEIPT2		(TPRTIDRECEIPT  |TPRSCPU2)
#define	TPRDIDRECEIPT3		(TPRTIDRECEIPT  |TPRSCPU3)
#define	TPRDIDRECEIPT4		(TPRTIDRECEIPT  |TPRSCPU4)
#define	TPRDIDRECEIPT5		(TPRTIDRECEIPT  |TPRSCPU5)
#define	TPRDIDRECEIPT6		(TPRTIDRECEIPT  |TPRSCPU6)

#define	TPRDIDTOKYURW1		(TPRTIDTOKYURW  |TPRSCPU1)
#define	TPRDIDTOKYURW2		(TPRTIDTOKYURW  |TPRSCPU2)
#define	TPRDIDTOKYURW3		(TPRTIDTOKYURW  |TPRSCPU3)
#define	TPRDIDTOKYURW4		(TPRTIDTOKYURW  |TPRSCPU4)
#define	TPRDIDTOKYURW5		(TPRTIDTOKYURW  |TPRSCPU5)
#define	TPRDIDTOKYURW6		(TPRTIDTOKYURW  |TPRSCPU6)

#define	TPRDIDDEBIT1		(TPRTIDDEBIT    |TPRSCPU1)
#define	TPRDIDDEBIT2		(TPRTIDDEBIT    |TPRSCPU2)
#define	TPRDIDDEBIT3		(TPRTIDDEBIT    |TPRSCPU3)
#define	TPRDIDDEBIT4		(TPRTIDDEBIT    |TPRSCPU4)
#define	TPRDIDDEBIT5		(TPRTIDDEBIT    |TPRSCPU5)
#define	TPRDIDDEBIT6		(TPRTIDDEBIT    |TPRSCPU6)

#define	TPRDIDGLORYCARD1	(TPRTIDGLORYCARD|TPRSCPU1)
#define	TPRDIDGLORYCARD2	(TPRTIDGLORYCARD|TPRSCPU2)
#define	TPRDIDGLORYCARD3	(TPRTIDGLORYCARD|TPRSCPU3)
#define	TPRDIDGLORYCARD4	(TPRTIDGLORYCARD|TPRSCPU4)
#define	TPRDIDGLORYCARD5	(TPRTIDGLORYCARD|TPRSCPU5)
#define	TPRDIDGLORYCARD6	(TPRTIDGLORYCARD|TPRSCPU6)

#define	TPRDIDVISMAC1		(TPRTIDVISMAC   |TPRSCPU1)
#define	TPRDIDVISMAC2		(TPRTIDVISMAC   |TPRSCPU2)
#define	TPRDIDVISMAC3		(TPRTIDVISMAC   |TPRSCPU3)
#define	TPRDIDVISMAC4		(TPRTIDVISMAC   |TPRSCPU4)
#define	TPRDIDVISMAC5		(TPRTIDVISMAC   |TPRSCPU5)
#define	TPRDIDVISMAC6		(TPRTIDVISMAC   |TPRSCPU6)

#define	TPRDIDPRSP1		(TPRTIDPRSP     |TPRSCPU1)
#define	TPRDIDPRSP2		(TPRTIDPRSP     |TPRSCPU2)
#define	TPRDIDPRSP3		(TPRTIDPRSP     |TPRSCPU3)
#define	TPRDIDPRSP4		(TPRTIDPRSP     |TPRSCPU4)
#define	TPRDIDPRSP5		(TPRTIDPRSP     |TPRSCPU5)
#define	TPRDIDPRSP6		(TPRTIDPRSP     |TPRSCPU6)

#define	TPRDIDMGC1JIS1		(TPRTIDMGC1JIS  |TPRSCPU1)
#define	TPRDIDMGC2JIS1		(TPRTIDMGC1JIS  |TPRSCPU2)
#define	TPRDIDMGC3JIS1		(TPRTIDMGC1JIS  |TPRSCPU3)
#define	TPRDIDMGC4JIS1		(TPRTIDMGC1JIS  |TPRSCPU4)
#define	TPRDIDMGC5JIS1		(TPRTIDMGC1JIS  |TPRSCPU5)
#define	TPRDIDMGC6JIS1		(TPRTIDMGC1JIS  |TPRSCPU6)

#define	TPRDIDMGC1JIS2		(TPRTIDMGC2JIS  |TPRSCPU1)
#define	TPRDIDMGC2JIS2		(TPRTIDMGC2JIS  |TPRSCPU2)
#define	TPRDIDMGC3JIS2		(TPRTIDMGC2JIS  |TPRSCPU3)
#define	TPRDIDMGC4JIS2		(TPRTIDMGC2JIS  |TPRSCPU4)
#define	TPRDIDMGC5JIS2		(TPRTIDMGC2JIS  |TPRSCPU5)
#define	TPRDIDMGC6JIS2		(TPRTIDMGC2JIS  |TPRSCPU6)

#define	TPRDIDGCAT1		(TPRTIDGCAT	|TPRSCPU1)
#define	TPRDIDGCAT2		(TPRTIDGCAT	|TPRSCPU2)
#define	TPRDIDGCAT3		(TPRTIDGCAT	|TPRSCPU3)
#define	TPRDIDGCAT4		(TPRTIDGCAT	|TPRSCPU4)
#define	TPRDIDGCAT5		(TPRTIDGCAT	|TPRSCPU5)
#define	TPRDIDGCAT6		(TPRTIDGCAT	|TPRSCPU6)

#define	TPRDIDPRT1		(TPRTIDPRT	|TPRSCPU1)
#define	TPRDIDPRT2		(TPRTIDPRT	|TPRSCPU2)
#define	TPRDIDPRT3		(TPRTIDPRT	|TPRSCPU3)
#define	TPRDIDPRT4		(TPRTIDPRT	|TPRSCPU4)
#define	TPRDIDPRT5		(TPRTIDPRT	|TPRSCPU5)
#define	TPRDIDPRT6		(TPRTIDPRT	|TPRSCPU6)

#define	TPRDIDLCDBRT1		(TPRTIDLCDBRT   |TPRSCPU1)
#define	TPRDIDLCDBRT2		(TPRTIDLCDBRT   |TPRSCPU2)
#define	TPRDIDLCDBRT3		(TPRTIDLCDBRT   |TPRSCPU3)
#define	TPRDIDLCDBRT4		(TPRTIDLCDBRT   |TPRSCPU4)
#define	TPRDIDLCDBRT5		(TPRTIDLCDBRT   |TPRSCPU5)
#define	TPRDIDLCDBRT6		(TPRTIDLCDBRT   |TPRSCPU6)

#define	TPRDIDPMOUSE1		(TPRTIDPMOUSE   |TPRSCPU1)
#define	TPRDIDPMOUSE2		(TPRTIDPMOUSE   |TPRSCPU2)
#define	TPRDIDPMOUSE3		(TPRTIDPMOUSE   |TPRSCPU3)
#define	TPRDIDPMOUSE4		(TPRTIDPMOUSE   |TPRSCPU4)
#define	TPRDIDPMOUSE5		(TPRTIDPMOUSE   |TPRSCPU5)
#define	TPRDIDPMOUSE6		(TPRTIDPMOUSE   |TPRSCPU6)

#define	TPRDIDSCALE1		(TPRTIDSCALE  |TPRSCPU1)
#define	TPRDIDSCALE2		(TPRTIDSCALE  |TPRSCPU2)
#define	TPRDIDSCALE3		(TPRTIDSCALE  |TPRSCPU3)
#define	TPRDIDSCALE4		(TPRTIDSCALE  |TPRSCPU4)
#define	TPRDIDSCALE5		(TPRTIDSCALE  |TPRSCPU5)
#define	TPRDIDSCALE6		(TPRTIDSCALE  |TPRSCPU6)

#define	TPRDIDORC1		(TPRTIDORC  |TPRSCPU1)
#define	TPRDIDORC2		(TPRTIDORC  |TPRSCPU2)
#define	TPRDIDORC3		(TPRTIDORC  |TPRSCPU3)
#define	TPRDIDORC4		(TPRTIDORC  |TPRSCPU4)
#define	TPRDIDORC5		(TPRTIDORC  |TPRSCPU5)
#define	TPRDIDORC6		(TPRTIDORC  |TPRSCPU6)

#define	TPRDIDSGSCALE1		(TPRTIDSGSCALE  |TPRSCPU1)
#define	TPRDIDSGSCALE2		(TPRTIDSGSCALE  |TPRSCPU2)
#define	TPRDIDSGSCALE3		(TPRTIDSGSCALE  |TPRSCPU3)
#define	TPRDIDSGSCALE4		(TPRTIDSGSCALE  |TPRSCPU4)
#define	TPRDIDSGSCALE5		(TPRTIDSGSCALE  |TPRSCPU5)
#define	TPRDIDSGSCALE6		(TPRTIDSGSCALE  |TPRSCPU6)

#define	TPRDIDSEGDISP1		(TPRTIDSEGDISP  |TPRSCPU1)
#define	TPRDIDSEGDISP2		(TPRTIDSEGDISP  |TPRSCPU2)
#define	TPRDIDSEGDISP3		(TPRTIDSEGDISP  |TPRSCPU3)
#define	TPRDIDSEGDISP4		(TPRTIDSEGDISP  |TPRSCPU4)
#define	TPRDIDSEGDISP5		(TPRTIDSEGDISP  |TPRSCPU5)
#define	TPRDIDSEGDISP6		(TPRTIDSEGDISP  |TPRSCPU6)

#define	TPRDIDCALLSW1		(TPRTIDCALLSW  |TPRSCPU1)
#define	TPRDIDCALLSW2		(TPRTIDCALLSW  |TPRSCPU2)
#define	TPRDIDCALLSW3		(TPRTIDCALLSW  |TPRSCPU3)
#define	TPRDIDCALLSW4		(TPRTIDCALLSW  |TPRSCPU4)
#define	TPRDIDCALLSW5		(TPRTIDCALLSW  |TPRSCPU5)
#define	TPRDIDCALLSW6		(TPRTIDCALLSW  |TPRSCPU6)

#define	TPRDIDDETECT1		(TPRTIDDETECT  |TPRSCPU1)
#define	TPRDIDDETECT2		(TPRTIDDETECT  |TPRSCPU2)
#define	TPRDIDDETECT3		(TPRTIDDETECT  |TPRSCPU3)
#define	TPRDIDDETECT4		(TPRTIDDETECT  |TPRSCPU4)
#define	TPRDIDDETECT5		(TPRTIDDETECT  |TPRSCPU5)
#define	TPRDIDDETECT6		(TPRTIDDETECT  |TPRSCPU6)

#define	TPRDIDSIGNP1		(TPRTIDSIGNP  |TPRSCPU1)
#define	TPRDIDSIGNP2		(TPRTIDSIGNP  |TPRSCPU2)
#define	TPRDIDSIGNP3		(TPRTIDSIGNP  |TPRSCPU3)
#define	TPRDIDSIGNP4		(TPRTIDSIGNP  |TPRSCPU4)
#define	TPRDIDSIGNP5		(TPRTIDSIGNP  |TPRSCPU5)
#define	TPRDIDSIGNP6		(TPRTIDSIGNP  |TPRSCPU6)

#define	TPRDIDEDY1		(TPRTIDEDY  |TPRSCPU1)
#define	TPRDIDEDY2		(TPRTIDEDY  |TPRSCPU2)
#define	TPRDIDEDY3		(TPRTIDEDY  |TPRSCPU3)
#define	TPRDIDEDY4		(TPRTIDEDY  |TPRSCPU4)
#define	TPRDIDEDY5		(TPRTIDEDY  |TPRSCPU5)
#define	TPRDIDEDY6		(TPRTIDEDY  |TPRSCPU6)

#define	TPRDIDCRWP1		(TPRTIDCRWP  |TPRSCPU1)
#define	TPRDIDCRWP2		(TPRTIDCRWP  |TPRSCPU2)
#define	TPRDIDCRWP3		(TPRTIDCRWP  |TPRSCPU3)
#define	TPRDIDCRWP4		(TPRTIDCRWP  |TPRSCPU4)
#define	TPRDIDCRWP5		(TPRTIDCRWP  |TPRSCPU5)
#define	TPRDIDCRWP6		(TPRTIDCRWP  |TPRSCPU6)

#define	TPRDIDSTPR1		(TPRTIDSTPR  |TPRSCPU1)
#define	TPRDIDSTPR2		(TPRTIDSTPR  |TPRSCPU2)
#define	TPRDIDSTPR3		(TPRTIDSTPR  |TPRSCPU3)
#define	TPRDIDSTPR4		(TPRTIDSTPR  |TPRSCPU4)
#define	TPRDIDSTPR5		(TPRTIDSTPR  |TPRSCPU5)
#define	TPRDIDSTPR6		(TPRTIDSTPR  |TPRSCPU6)

#define	TPRDIDPANA1		(TPRTIDPANA  |TPRSCPU1)
#define	TPRDIDPANA2		(TPRTIDPANA  |TPRSCPU2)
#define	TPRDIDPANA3		(TPRTIDPANA  |TPRSCPU3)
#define	TPRDIDPANA4		(TPRTIDPANA  |TPRSCPU4)
#define	TPRDIDPANA5		(TPRTIDPANA  |TPRSCPU5)
#define	TPRDIDPANA6		(TPRTIDPANA  |TPRSCPU6)

#define	TPRDIDGP1		(TPRTIDGP  |TPRSCPU1)
#define	TPRDIDGP2		(TPRTIDGP  |TPRSCPU2)
#define	TPRDIDGP3		(TPRTIDGP  |TPRSCPU3)
#define	TPRDIDGP4		(TPRTIDGP  |TPRSCPU4)
#define	TPRDIDGP5		(TPRTIDGP  |TPRSCPU5)
#define	TPRDIDGP6		(TPRTIDGP  |TPRSCPU6)

#define	TPRDIDS2PR1		(TPRTIDS2PR  |TPRSCPU1)
#define	TPRDIDS2PR2		(TPRTIDS2PR  |TPRSCPU2)
#define	TPRDIDS2PR3		(TPRTIDS2PR  |TPRSCPU3)
#define	TPRDIDS2PR4		(TPRTIDS2PR  |TPRSCPU4)
#define	TPRDIDS2PR5		(TPRTIDS2PR  |TPRSCPU5)
#define	TPRDIDS2PR6		(TPRTIDS2PR  |TPRSCPU6)

#define	TPRDIDPWRCTRL1	(TPRTIDPWRCTRL  |TPRSCPU1)
#define	TPRDIDPWRCTRL2	(TPRTIDPWRCTRL  |TPRSCPU2)
#define	TPRDIDPWRCTRL3	(TPRTIDPWRCTRL  |TPRSCPU3)
#define	TPRDIDPWRCTRL4	(TPRTIDPWRCTRL  |TPRSCPU4)
#define	TPRDIDPWRCTRL5	(TPRTIDPWRCTRL  |TPRSCPU5)
#define	TPRDIDPWRCTRL6	(TPRTIDPWRCTRL  |TPRSCPU6)

#define	TPRDIDPW1	(TPRTIDPW  |TPRSCPU1)
#define	TPRDIDPW2	(TPRTIDPW  |TPRSCPU2)
#define	TPRDIDPW3	(TPRTIDPW  |TPRSCPU3)
#define	TPRDIDPW4	(TPRTIDPW  |TPRSCPU4)
#define	TPRDIDPW5	(TPRTIDPW  |TPRSCPU5)
#define	TPRDIDPW6	(TPRTIDPW  |TPRSCPU6)

// <2004.07.09> mn
#define	TPRDIDCCR1	(TPRTIDCCR  |TPRSCPU1)
#define	TPRDIDCCR2	(TPRTIDCCR  |TPRSCPU2)
#define	TPRDIDCCR3	(TPRTIDCCR  |TPRSCPU3)
#define	TPRDIDCCR4	(TPRTIDCCR  |TPRSCPU4)
#define	TPRDIDCCR5	(TPRTIDCCR  |TPRSCPU5)
#define	TPRDIDCCR6	(TPRTIDCCR  |TPRSCPU6)
// ---- mn

#define	TPRDID57VFD1	(TPRTID57VFD  |TPRSCPU1)
#define	TPRDID57VFD2	(TPRTID57VFD  |TPRSCPU2)
#define	TPRDID57VFD3	(TPRTID57VFD  |TPRSCPU3)
#define	TPRDID57VFD4	(TPRTID57VFD  |TPRSCPU4)
#define	TPRDID57VFD5	(TPRTID57VFD  |TPRSCPU5)
#define	TPRDID57VFD6	(TPRTID57VFD  |TPRSCPU6)

#define	TPRDIDDISH1	(TPRTIDDISH  |TPRSCPU1)
#define	TPRDIDDISH2	(TPRTIDDISH  |TPRSCPU2)
#define	TPRDIDDISH3	(TPRTIDDISH  |TPRSCPU3)
#define	TPRDIDDISH4	(TPRTIDDISH  |TPRSCPU4)
#define	TPRDIDDISH5	(TPRTIDDISH  |TPRSCPU5)
#define	TPRDIDDISH6	(TPRTIDDISH  |TPRSCPU6)

#define	TPRDIDAIV1	(TPRTIDAIV  |TPRSCPU1)
#define	TPRDIDAIV2	(TPRTIDAIV  |TPRSCPU2)
#define	TPRDIDAIV3	(TPRTIDAIV  |TPRSCPU3)
#define	TPRDIDAIV4	(TPRTIDAIV  |TPRSCPU4)
#define	TPRDIDAIV5	(TPRTIDAIV  |TPRSCPU5)
#define	TPRDIDAIV6	(TPRTIDAIV  |TPRSCPU6)

#define	TPRDIDYOMOCA1	(TPRTIDYOMOCA  |TPRSCPU1)
#define	TPRDIDYOMOCA2	(TPRTIDYOMOCA  |TPRSCPU2)
#define	TPRDIDYOMOCA3	(TPRTIDYOMOCA  |TPRSCPU3)
#define	TPRDIDYOMOCA4	(TPRTIDYOMOCA  |TPRSCPU4)
#define	TPRDIDYOMOCA5	(TPRTIDYOMOCA  |TPRSCPU5)
#define	TPRDIDYOMOCA6	(TPRTIDYOMOCA  |TPRSCPU6)

#define	TPRDIDSMTPLUS1	(TPRTIDSMTPLUS  |TPRSCPU1)
#define	TPRDIDSMTPLUS2	(TPRTIDSMTPLUS  |TPRSCPU2)
#define	TPRDIDSMTPLUS3	(TPRTIDSMTPLUS  |TPRSCPU3)
#define	TPRDIDSMTPLUS4	(TPRTIDSMTPLUS  |TPRSCPU4)
#define	TPRDIDSMTPLUS5	(TPRTIDSMTPLUS  |TPRSCPU5)
#define	TPRDIDSMTPLUS6	(TPRTIDSMTPLUS  |TPRSCPU6)

#define	TPRDIDSUICA1	(TPRTIDSUICA	|TPRSCPU1)
#define	TPRDIDSUICA2	(TPRTIDSUICA	|TPRSCPU2)
#define	TPRDIDSUICA3	(TPRTIDSUICA	|TPRSCPU3)
#define	TPRDIDSUICA4	(TPRTIDSUICA	|TPRSCPU4)
#define	TPRDIDSUICA5	(TPRTIDSUICA	|TPRSCPU5)
#define	TPRDIDSUICA6	(TPRTIDSUICA	|TPRSCPU6)

#define	TPRDIDRFID1	(TPRTIDRFID	|TPRSCPU1)
#define	TPRDIDRFID2	(TPRTIDRFID	|TPRSCPU2)
#define	TPRDIDRFID3	(TPRTIDRFID	|TPRSCPU3)
#define	TPRDIDRFID4	(TPRTIDRFID	|TPRSCPU4)
#define	TPRDIDRFID5	(TPRTIDRFID	|TPRSCPU5)
#define	TPRDIDRFID6	(TPRTIDRFID	|TPRSCPU6)

#define	TPRDIDDISHT1	(TPRTIDDISHT  |TPRSCPU1)
#define	TPRDIDDISHT2	(TPRTIDDISHT  |TPRSCPU2)
#define	TPRDIDDISHT3	(TPRTIDDISHT  |TPRSCPU3)
#define	TPRDIDDISHT4	(TPRTIDDISHT  |TPRSCPU4)
#define	TPRDIDDISHT5	(TPRTIDDISHT  |TPRSCPU5)
#define	TPRDIDDISHT6	(TPRTIDDISHT  |TPRSCPU6)

#define	TPRDIDARSTTS1	(TPRTIDARSTTS  |TPRSCPU1)
#define	TPRDIDARSTTS2	(TPRTIDARSTTS  |TPRSCPU2)
#define	TPRDIDARSTTS3	(TPRTIDARSTTS  |TPRSCPU3)
#define	TPRDIDARSTTS4	(TPRTIDARSTTS  |TPRSCPU4)
#define	TPRDIDARSTTS5	(TPRTIDARSTTS  |TPRSCPU5)
#define	TPRDIDARSTTS6	(TPRTIDARSTTS  |TPRSCPU6)

#define	TPRDIDMCP1	(TPRTIDMCP  |TPRSCPU1)
#define	TPRDIDMCP2	(TPRTIDMCP  |TPRSCPU2)
#define	TPRDIDMCP3	(TPRTIDMCP  |TPRSCPU3)
#define	TPRDIDMCP4	(TPRTIDMCP  |TPRSCPU4)
#define	TPRDIDMCP5	(TPRTIDMCP  |TPRSCPU5)
#define	TPRDIDMCP6	(TPRTIDMCP  |TPRSCPU6)

#define	TPRDIDFCL1	(TPRTIDFCL  |TPRSCPU1)
#define	TPRDIDFCL2	(TPRTIDFCL  |TPRSCPU2)
#define	TPRDIDFCL3	(TPRTIDFCL  |TPRSCPU3)
#define	TPRDIDFCL4	(TPRTIDFCL  |TPRSCPU4)
#define	TPRDIDFCL5	(TPRTIDFCL  |TPRSCPU5)
#define	TPRDIDFCL6	(TPRTIDFCL  |TPRSCPU6)

#define	TPRDIDDRW1	(TPRTIDDRW  |TPRSCPU1)
#define	TPRDIDDRW2	(TPRTIDDRW  |TPRSCPU2)
#define	TPRDIDDRW3	(TPRTIDDRW  |TPRSCPU3)
#define	TPRDIDDRW4	(TPRTIDDRW  |TPRSCPU4)
#define	TPRDIDDRW5	(TPRTIDDRW  |TPRSCPU5)
#define	TPRDIDDRW6	(TPRTIDDRW  |TPRSCPU6)

#define	TPRDIDABSV311	(TPRTIDABSV31  |TPRSCPU1)
#define	TPRDIDABSV312	(TPRTIDABSV31  |TPRSCPU2)
#define	TPRDIDABSV313	(TPRTIDABSV31  |TPRSCPU3)
#define	TPRDIDABSV314	(TPRTIDABSV31  |TPRSCPU4)
#define	TPRDIDABSV315	(TPRTIDABSV31  |TPRSCPU5)
#define	TPRDIDABSV316	(TPRTIDABSV31  |TPRSCPU6)

#define	TPRDIDYAMATO1	(TPRTIDYAMATO  |TPRSCPU1)
#define	TPRDIDYAMATO2	(TPRTIDYAMATO  |TPRSCPU2)
#define	TPRDIDYAMATO3	(TPRTIDYAMATO  |TPRSCPU3)
#define	TPRDIDYAMATO4	(TPRTIDYAMATO  |TPRSCPU4)
#define	TPRDIDYAMATO5	(TPRTIDYAMATO  |TPRSCPU5)
#define	TPRDIDYAMATO6	(TPRTIDYAMATO  |TPRSCPU6)

#define	TPRDIDUSBCAM1	(TPRTIDUSBCAM  |TPRSCPU1)
#define	TPRDIDUSBCAM2	(TPRTIDUSBCAM  |TPRSCPU2)
#define	TPRDIDUSBCAM3	(TPRTIDUSBCAM  |TPRSCPU3)
#define	TPRDIDUSBCAM4	(TPRTIDUSBCAM  |TPRSCPU4)
#define	TPRDIDUSBCAM5	(TPRTIDUSBCAM  |TPRSCPU5)
#define	TPRDIDUSBCAM6	(TPRTIDUSBCAM  |TPRSCPU6)

#define	TPRDIDCCT1	(TPRTIDCCT  |TPRSCPU1)
#define	TPRDIDCCT2	(TPRTIDCCT  |TPRSCPU2)
#define	TPRDIDCCT3	(TPRTIDCCT  |TPRSCPU3)
#define	TPRDIDCCT4	(TPRTIDCCT  |TPRSCPU4)
#define	TPRDIDCCT5	(TPRTIDCCT  |TPRSCPU5)
#define	TPRDIDCCT6	(TPRTIDCCT  |TPRSCPU6)

#define	TPRDIDMASR1	(TPRTIDMASR  |TPRSCPU1)
#define	TPRDIDMASR2	(TPRTIDMASR  |TPRSCPU2)
#define	TPRDIDMASR3	(TPRTIDMASR  |TPRSCPU3)
#define	TPRDIDMASR4	(TPRTIDMASR  |TPRSCPU4)
#define	TPRDIDMASR5	(TPRTIDMASR  |TPRSCPU5)
#define	TPRDIDMASR6	(TPRTIDMASR  |TPRSCPU6)

#define	TPRDIDJMUPS1	(TPRTIDJMUPS  |TPRSCPU1)
#define	TPRDIDJMUPS2	(TPRTIDJMUPS  |TPRSCPU2)
#define	TPRDIDJMUPS3	(TPRTIDJMUPS  |TPRSCPU3)
#define	TPRDIDJMUPS4	(TPRTIDJMUPS  |TPRSCPU4)
#define	TPRDIDJMUPS5	(TPRTIDJMUPS  |TPRSCPU5)
#define	TPRDIDJMUPS6	(TPRTIDJMUPS  |TPRSCPU6)

#define TPRDIDSQRC1     (TPRTIDSQRC   |TPRSCPU1)
#define TPRDIDSQRC2     (TPRTIDSQRC   |TPRSCPU2)
#define TPRDIDSQRC3     (TPRTIDSQRC   |TPRSCPU3)
#define TPRDIDSQRC4     (TPRTIDSQRC   |TPRSCPU4)
#define TPRDIDSQRC5     (TPRTIDSQRC   |TPRSCPU5)
#define TPRDIDSQRC6     (TPRTIDSQRC   |TPRSCPU6)
#endif

#define TPRDIDICCARD1   (TPRTIDICCARD |TPRSCPU1)	/* 2015/02/02 */
#define TPRDIDICCARD2   (TPRTIDICCARD |TPRSCPU2)	/* 2015/02/02 */
#define TPRDIDICCARD3   (TPRTIDICCARD |TPRSCPU3)	/* 2015/02/02 */
#define TPRDIDICCARD4   (TPRTIDICCARD |TPRSCPU4)	/* 2015/02/02 */
#define TPRDIDICCARD5   (TPRTIDICCARD |TPRSCPU5)	/* 2015/02/02 */
#define TPRDIDICCARD6   (TPRTIDICCARD |TPRSCPU6)	/* 2015/02/02 */

#define TPRDIDMST1      (TPRTIDMST |TPRSCPU1)		/* 2015/07/14 */
#define TPRDIDMST2      (TPRTIDMST |TPRSCPU2)		/* 2015/07/14 */
#define TPRDIDMST3      (TPRTIDMST |TPRSCPU3)		/* 2015/07/14 */
#define TPRDIDMST4      (TPRTIDMST |TPRSCPU4)		/* 2015/07/14 */
#define TPRDIDMST5      (TPRTIDMST |TPRSCPU5)		/* 2015/07/14 */
#define TPRDIDMST6      (TPRTIDMST |TPRSCPU6)		/* 2015/07/14 */

#define TPRDIDPOWLI1    (TPRTIDPOWLI |TPRSCPU1)
#define TPRDIDPOWLI2    (TPRTIDPOWLI |TPRSCPU2)
#define TPRDIDPOWLI3    (TPRTIDPOWLI |TPRSCPU3)
#define TPRDIDPOWLI4    (TPRTIDPOWLI |TPRSCPU4)
#define TPRDIDPOWLI5    (TPRTIDPOWLI |TPRSCPU5)
#define TPRDIDPOWLI6    (TPRTIDPOWLI |TPRSCPU6)

#define	TPRDIDPSENSOR1	(TPRTIDPSENSOR   |TPRSCPU1)
#define	TPRDIDPSENSOR2	(TPRTIDPSENSOR   |TPRSCPU2)
#define	TPRDIDPSENSOR3	(TPRTIDPSENSOR   |TPRSCPU3)
#define	TPRDIDPSENSOR4	(TPRTIDPSENSOR   |TPRSCPU4)
#define	TPRDIDPSENSOR5	(TPRTIDPSENSOR   |TPRSCPU5)
#define	TPRDIDPSENSOR6	(TPRTIDPSENSOR   |TPRSCPU6)

#define	TPRDIDAPBF1	(TPRTIDAPBF |TPRSCPU1)
#define	TPRDIDAPBF2	(TPRTIDAPBF |TPRSCPU2)
#define	TPRDIDAPBF3	(TPRTIDAPBF |TPRSCPU3)
#define	TPRDIDAPBF4	(TPRTIDAPBF |TPRSCPU4)
#define	TPRDIDAPBF5	(TPRTIDAPBF |TPRSCPU5)
#define	TPRDIDAPBF6	(TPRTIDAPBF |TPRSCPU6)

#define TPRDIDSCALERM1  (TPRTIDSCALERM |TPRSCPU1)
#define TPRDIDSCALERM2  (TPRTIDSCALERM |TPRSCPU2)
#define TPRDIDSCALERM3  (TPRTIDSCALERM |TPRSCPU3)
#define TPRDIDSCALERM4  (TPRTIDSCALERM |TPRSCPU4)
#define TPRDIDSCALERM5  (TPRTIDSCALERM |TPRSCPU5)
#define TPRDIDSCALERM6  (TPRTIDSCALERM |TPRSCPU6)

#define TPRDIDEXC1	(TPRTIDEXC |TPRSCPU1)
#define TPRDIDEXC2	(TPRTIDEXC |TPRSCPU2)
#define TPRDIDEXC3	(TPRTIDEXC |TPRSCPU3)
#define TPRDIDEXC4	(TPRTIDEXC |TPRSCPU4)
#define TPRDIDEXC5	(TPRTIDEXC |TPRSCPU5)
#define TPRDIDEXC6	(TPRTIDEXC |TPRSCPU6)

#define TPRDIDHITOUCH1	(TPRTIDHITOUCH |TPRSCPU1)
#define TPRDIDHITOUCH2	(TPRTIDHITOUCH |TPRSCPU2)
#define TPRDIDHITOUCH3	(TPRTIDHITOUCH |TPRSCPU3)
#define TPRDIDHITOUCH4	(TPRTIDHITOUCH |TPRSCPU4)
#define TPRDIDHITOUCH5	(TPRTIDHITOUCH |TPRSCPU5)
#define TPRDIDHITOUCH6	(TPRTIDHITOUCH |TPRSCPU6)

#define TPRDIDAMI1	(TPRTIDAMI |TPRSCPU1)
#define TPRDIDAMI2	(TPRTIDAMI |TPRSCPU2)
#define TPRDIDAMI3	(TPRTIDAMI |TPRSCPU3)
#define TPRDIDAMI4	(TPRTIDAMI |TPRSCPU4)
#define TPRDIDAMI5	(TPRTIDAMI |TPRSCPU5)
#define TPRDIDAMI6	(TPRTIDAMI |TPRSCPU6)

#define TPRDIDSCALE_SKS1	(TPRTIDSCALE_SKS |TPRSCPU1)
#define TPRDIDSCALE_SKS2	(TPRTIDSCALE_SKS |TPRSCPU2)
#define TPRDIDSCALE_SKS3	(TPRTIDSCALE_SKS |TPRSCPU3)
#define TPRDIDSCALE_SKS4	(TPRTIDSCALE_SKS |TPRSCPU4)
#define TPRDIDSCALE_SKS5	(TPRTIDSCALE_SKS |TPRSCPU5)
#define TPRDIDSCALE_SKS6	(TPRTIDSCALE_SKS |TPRSCPU6)

/* End of tprdid.h */
