#ifndef __tprmid_h
#define __tprmid_h

/* System *//* notification message */
#define TPRMID_NOP		0x00000000		/* no operation message */
#define	TPRMID_SYSFAIL		(TPRMODEREQ|TPRIPCSYSFAIL|0)
#define	TPRMID_SYSFAILACK	(TPRMODEACK|TPRIPCSYSFAIL|0)
#define	TPRMID_SYSFAILWAIT	(TPRMODEBUSY|TPRIPCSYSFAIL|0)
#define	TPRMID_SYSFAILWAITEND	(TPRMODEBUSY|TPRIPCSYSFAIL|1)
#define	TPRMID_SYSREBOOT	(TPRMODEBUSY|TPRIPCSYSFAIL|2)

/* mode */
#define	TPRMODENOTICE	0x00000000		/* notice */
#define	TPRMODEREQ	0x01000000		/* request */
#define	TPRMODEACK	0x02000000		/* ack */
#define	TPRMODEBUSY	0x04000000		/* busy */
/* message id (basic) */
#define	TPRIPCSYSFAIL	(0x80000000|0x0000ff00)
#define	TPRIPCREADY	0x00100000
#define	TPRIPCNREADY	0x00200000
#define	TPRIPCCREADY	0x00300000
#define	TPRIPCNCREADY	0x00400000
#define	TPRIPCSNTF	0x00500000
#define	TPRIPCTIM	0x00600000
#define	TPRIPCDIAG	0x00700000
#define	TPRIPCDEV	0x00800000
#define	TPRIPCAPL	0x00900000

	/* task status */
#define	TPRMID_READY		(TPRMODENOTICE|TPRIPCREADY|0)
#define	TPRMID_NO_READY		(TPRMODENOTICE|TPRIPCNREADY|0)
#define	TPRMID_CO_READY		(TPRMODENOTICE|TPRIPCCREADY|0)
#define	TPRMID_NO_CO_READY	(TPRMODENOTICE|TPRIPCNCREADY|0)

	/* system notice information */
#define	TPRMID_SYSNOTIFY	(TPRMODEREQ|TPRIPCSNTF|0)
#define	TPRMID_SYSNOTIFYACK	(TPRMODEACK|TPRIPCSNTF|0)

	/* timer task */
#define	TPRMID_TIMREQ		(TPRMODEREQ|TPRIPCTIM|0)
#define	TPRMID_TIM		(TPRMODEACK|TPRIPCTIM|0)

	/* diag */
#define	TPRMID_DIAGREQ		(TPRMODEREQ|TPRIPCDIAG|0)
#define	TPRMID_DIAGACK		(TPRMODEACK|TPRIPCDIAG|0)

	/* device driver */
#define	TPRMID_DEVREQ		(TPRMODEREQ|TPRIPCDEV|0)
#define	TPRMID_DEVACK		(TPRMODEACK|TPRIPCDEV|0)
#define	TPRMID_DEVNOTIFY	(TPRMODENOTICE|TPRIPCDEV|0)

	/* apl module */
#define	TPRMID_APLREQ		(TPRMODEREQ|TPRIPCAPL|0)
#define	TPRMID_APLACK		(TPRMODEACK|TPRIPCAPL|0)
#define	TPRMID_APLNOTIFY	(TPRMODENOTICE|TPRIPCAPL|0)

#endif
/* End of tprmid.h */
