import 'csvbkupJsonFile_test.dart';
import 'fjssJsonFile_test.dart';
import 'specificftpJsonFile_test.dart';
import 'hqftpJsonFile_test.dart';
import 'hqhistJsonFile_test.dart';
import 'hqprodJsonFile_test.dart';
import 'movie_infoJsonFile_test.dart';
import 'qs_movie_start_dspJsonFile_test.dart';
import 'qc_start_dspJsonFile_test.dart';
import 'f_self_contentJsonFile_test.dart';
import 'f_self_imgJsonFile_test.dart';
import 'rsv_custrealJsonFile_test.dart';
import 'imageJsonFile_test.dart';
import 'mm_rept_taxchgJsonFile_test.dart';
import 'add_partsJsonFile_test.dart';
import 'set_optionJsonFile_test.dart';
import 'lotteryJsonFile_test.dart';
import 'colorfip15JsonFile_test.dart';
import 'taxfree_chgJsonFile_test.dart';
import 'tpointJsonFile_test.dart';
import 'tpoint_dummyJsonFile_test.dart';
import 'wiz_cnctJsonFile_test.dart';
import 'mupdate_counterJsonFile_test.dart';
import 'update_counterJsonFile_test.dart';
import 'bm_missmachJsonFile_test.dart';
import 'quick_selfJsonFile_test.dart';
import 'systemCheckJsonFile_test.dart';
import 'quick_self_edyJsonFile_test.dart';
import 'quick_self_suicaJsonFile_test.dart';
import 'quick_self_pasmoJsonFile_test.dart';
import 'cnct_sioJsonFile_test.dart';


void main() {
  csvbkupJsonFile_test();
  fjssJsonFile_test();
  specificftpJsonFile_test();
  hqftpJsonFile_test();
  hqhistJsonFile_test();
  hqprodJsonFile_test();
  movie_infoJsonFile_test();
  qs_movie_start_dspJsonFile_test();
  qc_start_dspJsonFile_test();
  f_self_contentJsonFile_test();
  f_self_imgJsonFile_test();
  rsv_custrealJsonFile_test();
  imageJsonFile_test();
  mm_rept_taxchgJsonFile_test();
  add_partsJsonFile_test();
  set_optionJsonFile_test();
  lotteryJsonFile_test();
  colorfip15JsonFile_test();
  taxfree_chgJsonFile_test();
  tpointJsonFile_test();
  tpoint_dummyJsonFile_test();
  wiz_cnctJsonFile_test();
  mupdate_counterJsonFile_test();
  update_counterJsonFile_test();
  bm_missmachJsonFile_test();
  quick_selfJsonFile_test();
  systemCheckJsonFile_test();
  quick_self_edyJsonFile_test();
  quick_self_suicaJsonFile_test();
  quick_self_pasmoJsonFile_test();
  cnct_sioJsonFile_test();
}
