import 'proc_conJsonFile_test.dart';
import 'mkey_2800_1JsonFile_test.dart';
import 'mkey_2800_2JsonFile_test.dart';
import 'repeat_toolJsonFile_test.dart';
import 'msr_chkJsonFile_test.dart';
import 'scan_plus_1JsonFile_test.dart';
import 'scan_plus_2JsonFile_test.dart';
import 'scan_2800_1JsonFile_test.dart';
import 'scan_2800_2JsonFile_test.dart';
import 'scan_2800ip_1JsonFile_test.dart';
import 'scan_2800ip_2JsonFile_test.dart';
import 'scan_2800im_1JsonFile_test.dart';
import 'scan_2800im_2JsonFile_test.dart';
import 'scan_2800a3_1JsonFile_test.dart';
import 'scan_2800i3_1JsonFile_test.dart';
import 'scan_2800_3JsonFile_test.dart';
import 'scan_2800_4JsonFile_test.dart';
import 'sm_scalescJsonFile_test.dart';
import 'staffJsonFile_test.dart';
import 'tprtfJsonFile_test.dart';
import 'tprtfJsonFile_test.dart';
import 'tprtimJsonFile_test.dart';
import 'tprtsJsonFile_test.dart';
import 'tprtssJsonFile_test.dart';
import 'tprtss2JsonFile_test.dart';


void main() {
  proc_conJsonFile_test();
  mkey_2800_1JsonFile_test();
  mkey_2800_2JsonFile_test();
  repeat_toolJsonFile_test();
  msr_chkJsonFile_test();
  scan_plus_1JsonFile_test();
  scan_plus_2JsonFile_test();
  scan_2800_1JsonFile_test();
  scan_2800_2JsonFile_test();
  scan_2800ip_1JsonFile_test();
  scan_2800ip_2JsonFile_test();
  scan_2800im_1JsonFile_test();
  scan_2800im_2JsonFile_test();
  scan_2800a3_1JsonFile_test();
  scan_2800i3_1JsonFile_test();
  scan_2800_3JsonFile_test();
  scan_2800_4JsonFile_test();
  sm_scalescJsonFile_test();
  staffJsonFile_test();
  tprtfJsonFile_test();
  tprtimJsonFile_test();
  tprtsJsonFile_test();
  tprtssJsonFile_test();
  tprtss2JsonFile_test();
}
