import 'absv31JsonFile_test.dart';
import 'acbJsonFile_test.dart';
import 'acb20JsonFile_test.dart';
import 'acb50JsonFile_test.dart';
import 'acrJsonFile_test.dart';
import 'aivJsonFile_test.dart';
import 'ar_stts_01JsonFile_test.dart';
import 'ccrJsonFile_test.dart';
import 'cctJsonFile_test.dart';
import 'dishJsonFile_test.dart';
import 'dishtJsonFile_test.dart';
import 'fal2JsonFile_test.dart';
import 'fclJsonFile_test.dart';
import 'gcat_cnctJsonFile_test.dart';
import 'gpJsonFile_test.dart';
import 'jmupsJsonFile_test.dart';
import 'jrw_multiJsonFile_test.dart';
import 'masrJsonFile_test.dart';
import 'mcp200JsonFile_test.dart';
import 'orcJsonFile_test.dart';
import 'panaJsonFile_test.dart';
import 'psp60JsonFile_test.dart';
import 'psp70JsonFile_test.dart';
import 'pw410JsonFile_test.dart';
import 'pwrctrlJsonFile_test.dart';
import 'rewrite_cardJsonFile_test.dart';
import 'rfidJsonFile_test.dart';
import 's2prJsonFile_test.dart';
import 'scaleJsonFile_test.dart';
import 'sip60JsonFile_test.dart';
import 'sm_scale1JsonFile_test.dart';
import 'sm_scale2JsonFile_test.dart';
import 'stprJsonFile_test.dart';
import 'vega3000JsonFile_test.dart';
import 'vismacJsonFile_test.dart';
import 'yamatoJsonFile_test.dart';
import 'yomocaJsonFile_test.dart';

void main() {
  absv31JsonFile_test();
  acbJsonFile_test();
  acb20JsonFile_test();
  acb50JsonFile_test();
  acrJsonFile_test();
  aivJsonFile_test();
  ar_stts_01JsonFile_test();
  ccrJsonFile_test();
  cctJsonFile_test();
  dishJsonFile_test();
  dishtJsonFile_test();
  fal2JsonFile_test();
  fclJsonFile_test();
  gcat_cnctJsonFile_test();
  gpJsonFile_test();
  jmupsJsonFile_test();
  jrw_multiJsonFile_test();
  masrJsonFile_test();
  mcp200JsonFile_test();
  orcJsonFile_test();
  panaJsonFile_test();
  psp60JsonFile_test();
  psp70JsonFile_test();
  pw410JsonFile_test();
  pwrctrlJsonFile_test();
  rewrite_cardJsonFile_test();
  rfidJsonFile_test();
  s2prJsonFile_test();
  scaleJsonFile_test();
  sip60JsonFile_test();
  sm_scale1JsonFile_test();
  sm_scale2JsonFile_test();
  stprJsonFile_test();
  vega3000JsonFile_test();
  vismacJsonFile_test();
  yamatoJsonFile_test();
  yomocaJsonFile_test();
}
