/*
 * (C)2024 TERAOKA SEIKO Co., Ltd./株式会社寺岡精工
 * CONFIDENTIAL/社外秘
 * 無断開示・無断複製禁止
 */

///  関連tprxソース: pPromschMst.h - pPromschMst
class PpromschMst {
  int compCd = 0; // 企業コード
  int streCd = 0; // 店舗コード
  String planCd = ""; // 企画コード
  int promCd = 0; // プロモーションコード
  int promTyp = 0; // 企画タイプ
  int schTyp = 0; // スケジュールタイプ
  String promName = ""; // プロモーション名称
  int rewardVal = 0; // 特典値
  String itemCd = ""; // コード
  int lrgclsCd = 0; // 大分類コード
  int mdlclsCd = 0; // 中分類コード
  int smlclsCd = 0; // 小分類コード
  int tnyclsCd = 0; // クラスコード
  int dscVal = 0; // 値引値
  double cost = 0; // 原価
  double costPer = 0; // 原価率
  int custDscVal = 0; // 会員値引値
  int formQty1 = 0; // 成立個数1
  int formQty2 = 0; // 成立個数2
  int formQty3 = 0; // 成立個数3
  int formQty4 = 0; // 成立個数4
  int formQty5 = 0; // 成立個数5
  int formPrc1 = 0; // 成立金額1
  int formPrc2 = 0; // 成立金額2
  int formPrc3 = 0; // 成立金額3
  int formPrc4 = 0; // 成立金額4
  int formPrc5 = 0; // 成立金額5
  int custFormPrc1 = 0; // 会員成立金額1
  int custFormPrc2 = 0; // 会員成立金額2
  int custFormPrc3 = 0; // 会員成立金額3
  int custFormPrc4 = 0; // 会員成立金額4
  int custFormPrc5 = 0; // 会員成立金額5
  int avPrc = 0; // 成立後平均単価
  int custAvPrc = 0; // 成立後会員平均単価
  int avPrcAdptFlg = 0; // 成立後平均単価使用フラグ
  int avPrcUtilFlg = 0; // 成立後平均単価利用フラグ
  int lowLimit = 0; // 成立下限額
  int svsTyp = 0; // サービスタイプ
  int dscTyp = 0; // 値引割引タイプ
  int recLimit = 0; // レシート単位制限個数
  int recBuyLimit = 0; // レシート単位購入制限個数
  String startDatetime = ""; // 開始日時
  String endDatetime = ""; // 終了日時
  int timeschFlg = 0; // タイムスケジュールフラグ
  int sunFlg = 0; // 曜日フラグ・日
  int monFlg = 0; // 曜日フラグ・月
  int tueFlg = 0; // 曜日フラグ・火
  int wedFlg = 0; // 曜日フラグ・水
  int thuFlg = 0; // 曜日フラグ・木
  int friFlg = 0; // 曜日フラグ・金
  int satFlg = 0; // 曜日フラグ・土
  int eachschTyp = 0; // 特定スケジュールタイプ
  String eachschFlg = ""; // 特定スケジュール
  int stopFlg = 0; // 中断フラグ
  int minPrc = 0; // 下限額
  int maxPrc = 0; // 上限額
  int taxFlg = 0; // 税金額対象フラグ
  int memberQty = 0; // セットマッチ構成種類
  int divCd = 0; // 売価変更理由区分コード
  int acctCd = 0; // アカウントＩＤ
  String promoExtId = ""; // 上位システム識別企画番号
  int trendsTyp = 0; // システムフラグ
  int userVal1 = 0; // ユーザー別フィールド１
  int userVal2 = 0; // ユーザー別フィールド２
  int userVal3 = 0; // ユーザー別フィールド３
  int userVal4 = 0; // ユーザー別フィールド４
  int userVal5 = 0; // ユーザー別フィールド５
  String userVal6 = ""; // ユーザー別フィールド６
  String insDatetime = ""; // 作成日時
  String updDatetime = ""; // 更新日時
  int status = 0; // 状態
  int sendFlg = 0; // 送信フラグ
  int updUser = 0; // 最終更新者
  int updSystem = 0; // 更新元システム
  double pointAddMagn = 0; // ポイント割増倍率（倍）
  int pointAddMemTyp = 0; // 割増ポイント会員区分
  double svsClsFData1 = 0; // サービス分類小数データ1
  int svsClsSData1 = 0; // サービス分類フラグデータ1
  int svsClsSData2 = 0; // サービス分類フラグデータ2
  int svsClsSData3 = 0; // サービス分類フラグデータ3
  double pluPtsRate = 0; // 商品ポイント倍率
  int custSvsUnit = 0; // 顧客サービス基準値
  int refAcct = 0; // 参照アカウント
  String linkedPromId = ""; // 連動企画
  int dateFlg1 = 0; // 日付フラグ１
  int dateFlg2 = 0; // 日付フラグ２
  int dateFlg3 = 0; // 日付フラグ３
  int dateFlg4 = 0; // 日付フラグ４
  int dateFlg5 = 0; // 日付フラグ５
}
